KOGITO-6607 adding user jdoe to requests
apache/incubator-kie-examples pull request #1237
Opened 2022-04-27 10:37 UTC by uteegozi

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `main` branch!**

- [x ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ x] Pull Request contains link to the JIRA issue
- [ x] Pull Request contains link to any dependent or related Pull Request
- [ x] Pull Request contains description of the issue
- [ x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
After assigning user tasks to a specific user in PR https://github.com/kiegroup/kogito-examples/pull/1179 requests need to be sent with the relevant user as parameter. 
The user jdoe was added to the example requests on the Readme file of the Kogito Extended Travel example.

Jira Issue: https://issues.redhat.com/browse/KOGITO-6607
Related PR: https://github.com/kiegroup/kogito-examples/pull/1179
</summary>

</details>

2022-04-28 03:09 UTC, cristianonicolai approved these changes

2022-04-28 03:09 UTC, cristianonicolai commented
ok to test

2022-04-28 03:10 UTC, cristianonicolai commented
jenkins please retest this

2022-04-28 07:50 UTC, radtriste requested changes
Could you also add the `visas` changes ?

2022-04-28 07:50 UTC, radtriste commented on kogito-quarkus-examples/kogito-travel-agency/extended/travels/README.md
> +### GET /travels/{id}/tasks?user=jdoe
Please remove this from titles, I don't think it makes sense. Only the command is useful.

2022-04-29 06:45 UTC, uteegozi commented on kogito-quarkus-examples/kogito-travel-agency/extended/travels/README.md
> +### GET /travels/{id}/tasks?user=jdoe
Will remove from titles and also update Visas Readme

2022-05-02 12:32 UTC, uteegozi commented on kogito-quarkus-examples/kogito-travel-agency/extended/travels/README.md
> +### GET /travels/{id}/tasks?user=jdoe
[b73e1de](https://github.com/kiegroup/kogito-examples/pull/1237/commits/b73e1de76033d3b82d248a93055a157949aa3b61)
In addition removing user jdoe from the titles we also added user alice to the relevant visa requests and fixed payloads where needed.

2022-05-03 14:20 UTC, radtriste approved these changes
tested all good for me. thx !

2022-05-03 14:20 UTC, merged