[KOGITO-1023] consolidate kogito-bom and kogito-runtimes repos
apache/incubator-kie-examples pull request #130
Opened 2020-02-07 16:39 UTC by mariofusco

2020-02-12 08:55 UTC, MarianMacik requested changes

2020-02-12 08:55 UTC, MarianMacik commented on pom.xml
Still inheriting from kogito-bom-parent.

2020-02-12 09:03 UTC, MarianMacik commented
Also please delete `kogito-bom` stage from `Jenkinsfile`:
https://github.com/kiegroup/kogito-examples/blob/83586f0107ddc9c89d5916a6dc76d9b944678a4d/Jenkinsfile#L21-L30

2020-02-21 16:09 UTC, evacchi approved these changes
I think it should be ok now

2020-02-21 17:58 UTC, merged