KOGITO-8163 add devui and source add on in examples
apache/incubator-kie-examples pull request #1448
Opened 2022-10-19 19:34 UTC by AjayJagan

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `main` branch!**

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-lts</b>
 
- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [kogito-examples] mandrel</b>

- for <b>mandrel lts checks</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins run mandrel-lts</b>

- for a <b>specific mandrel lts check</b>  
  Run native checks against Mandrel image and quarkus lts branch 
  Please add comment: <b>Jenkins (re)run [kogito-examples] mandrel-lts</b>
 
</details>

2022-10-19 20:48 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#409` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/409/display/redirect

**Test results:**
- PASSED: 362
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-10-19T20:47:30.046Z]     at org.kie.kogito.codegen.process.ProcessCodegen.<init> (ProcessCodegen.java:258)<br/>[2022-10-19T20:47:30.046Z]     at org.kie.kogito.codegen.process.ProcessCodegen.ofProcesses (ProcessCodegen.java:228)<br/>[2022-10-19T20:47:30.046Z]     at org.kie.kogito.codegen.process.ProcessCodegen.ofCollectedResources (ProcessCodegen.java:156)<br/>[2022-10-19T20:47:30.046Z]     at org.kie.kogito.codegen.process.ProcessCodegenFactory.create (ProcessCodegenFactory.java:29)<br/>[2022-10-19T20:47:30.046Z]     at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.lambda$loadGenerators$0 (ApplicationGeneratorDiscovery.java:60)<br/>[2022-10-19T20:47:30.046Z]     at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:195)<br/>[2022-10-19T20:47:30.046Z]     at java.util.Iterator.forEachRemaining (Iterator.java:133)<br/>[2022-10-19T20:47:30.046Z]     at java.util.Spliterators$IteratorSpliterator.forEachRemaining (Spliterators.java:1801)<br/>[2022-10-19T20:47:30.046Z]     at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:484)<br/>[2022-10-19T20:47:30.046Z]     at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:474)<br/>[2022-10-19T20:47:30.046Z]     at java.util.stream.ReduceOps$ReduceOp.evaluateSequential (ReduceOps.java:913)<br/>[2022-10-19T20:47:30.046Z]     at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)<br/>[2022-10-19T20:47:30.046Z]     at java.util.stream.ReferencePipeline.collect (ReferencePipeline.java:578)<br/>[2022-10-19T20:47:30.046Z]     at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.loadGenerators (ApplicationGeneratorDiscovery.java:62)<br/>[2022-10-19T20:47:30.046Z]     at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.discover (ApplicationGeneratorDiscovery.java:48)<br/>[2022-10-19T20:47:30.046Z]     at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateFiles (KogitoAssetsProcessor.java:262)<br/>[2022-10-19T20:47:30.046Z]     at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateSources (KogitoAssetsProcessor.java:140)<br/>[2022-10-19T20:47:30.046Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2022-10-19T20:47:30.046Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2022-10-19T20:47:30.046Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2022-10-19T20:47:30.046Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2022-10-19T20:47:30.046Z]     at io.quarkus.deployment.ExtensionLoader$3.execute (ExtensionLoader.java:909)<br/>[2022-10-19T20:47:30.046Z]     at io.quarkus.builder.BuildContext.run (BuildContext.java:281)<br/>[2022-10-19T20:47:30.046Z]     at org.jboss.threads.ContextHandler$1.runWith (ContextHandler.java:18)<br/>[2022-10-19T20:47:30.046Z]     at org.jboss.threads.EnhancedQueueExecutor$Task.run (EnhancedQueueExecutor.java:2449)<br/>[2022-10-19T20:47:30.046Z]     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run (EnhancedQueueExecutor.java:1478)<br/>[2022-10-19T20:47:30.046Z]     at java.lang.Thread.run (Thread.java:829)<br/>[2022-10-19T20:47:30.046Z]     at org.jboss.threads.JBossThread.run (JBossThread.java:501)<br/>[2022-10-19T20:47:30.046Z] [ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.13.2.Final:build (default) on project serverless-workflow-service-calls-quarkus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/>[2022-10-19T20:47:30.046Z] [ERROR] 	[error]: Build step org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor#generateSources threw an exception: org.kie.kogito.codegen.process.ProcessCodegenException: Duplicated process with id jsonservicecall found in the project, please review .bpmn files<br/>[2022-10-19T20:47:30.046Z] [ERROR] 	at org.kie.kogito.codegen.process.ProcessCodegen.<init>(ProcessCodegen.java:258)<br/>[2022-10-19T20:47:30.046Z] [ERROR] 	at org.kie.kogito.codegen.process.ProcessCodegen.ofProcesses(ProcessCodegen.java:228)<br/>[2022-10-19T20:47:30.046Z] [ERROR] 	at org.kie.kogito.codegen.process.ProcessCodegen.ofCollectedResources(ProcessCodegen.java:156)<br/>[2022-10-19T20:47:30.046Z] [ERROR] 	at org.kie.kogito.codegen.process.ProcessCodegenFactory.create(ProcessCodegenFactory.java:29)<br/>[2022-10-19T20:47:30.046Z] [ERROR] 	at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.lambda$loadGenerators$0(ApplicationGeneratorDiscovery.java:60)<br/>[2022-10-19T20:47:30.046Z] [ERROR] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)<br/>[2022-10-19T20:47:30.046Z] [ERROR] 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)<br/>[2022-10-19T20:47:30.046Z] [ERROR] 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)<br/>[2022-10-19T20:47:30.046Z] [ERROR] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)<br/>[2022-10-19T20:47:30.046Z] [ERROR] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)<br/>[2022-10-19T20:47:30.046Z] [ERROR] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)<br/>[2022-10-19T20:47:30.046Z] [ERROR] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>[2022-10-19T20:47:30.046Z] [ERROR] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)<br/>[2022-10-19T20:47:30.046Z] [ERROR] 	at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.loadGenerators(ApplicationGeneratorDiscovery.java:62)<br/>[2022-10-19T20:47:30.046Z] [ERROR] 	at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.discover(ApplicationGeneratorDiscovery.java:48)<br/>[2022-10-19T20:47:30.046Z] [ERROR] 	at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateFiles(KogitoAssetsProcessor.java:262)<br/>[2022-10-19T20:47:30.046Z] [ERROR] 	at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateSources(KogitoAssetsProcessor.java:140)<br/>[2022-10-19T20:47:30.047Z] [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>[2022-10-19T20:47:30.047Z] [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>[2022-10-19T20:47:30.047Z] [ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>[2022-10-19T20:47:30.047Z] [ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>[2022-10-19T20:47:30.047Z] [ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)<br/>[2022-10-19T20:47:30.047Z] [ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)<br/>[2022-10-19T20:47:30.047Z] [ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/>[2022-10-19T20:47:30.047Z] [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)<br/>[2022-10-19T20:47:30.047Z] [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)<br/>[2022-10-19T20:47:30.047Z] [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)<br/>[2022-10-19T20:47:30.047Z] [ERROR] 	at org.jboss.threads.JBossThread.run(JBossThrea [...]

2022-10-20 08:01 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#411` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/411/display/redirect

**Test results:**
- PASSED: 362
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-10-20T08:01:02.424Z]     at org.kie.kogito.codegen.process.ProcessCodegen.<init> (ProcessCodegen.java:258)<br/>[2022-10-20T08:01:02.424Z]     at org.kie.kogito.codegen.process.ProcessCodegen.ofProcesses (ProcessCodegen.java:228)<br/>[2022-10-20T08:01:02.424Z]     at org.kie.kogito.codegen.process.ProcessCodegen.ofCollectedResources (ProcessCodegen.java:156)<br/>[2022-10-20T08:01:02.424Z]     at org.kie.kogito.codegen.process.ProcessCodegenFactory.create (ProcessCodegenFactory.java:29)<br/>[2022-10-20T08:01:02.424Z]     at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.lambda$loadGenerators$0 (ApplicationGeneratorDiscovery.java:60)<br/>[2022-10-20T08:01:02.424Z]     at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:195)<br/>[2022-10-20T08:01:02.424Z]     at java.util.Iterator.forEachRemaining (Iterator.java:133)<br/>[2022-10-20T08:01:02.424Z]     at java.util.Spliterators$IteratorSpliterator.forEachRemaining (Spliterators.java:1801)<br/>[2022-10-20T08:01:02.424Z]     at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:484)<br/>[2022-10-20T08:01:02.424Z]     at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:474)<br/>[2022-10-20T08:01:02.424Z]     at java.util.stream.ReduceOps$ReduceOp.evaluateSequential (ReduceOps.java:913)<br/>[2022-10-20T08:01:02.424Z]     at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)<br/>[2022-10-20T08:01:02.424Z]     at java.util.stream.ReferencePipeline.collect (ReferencePipeline.java:578)<br/>[2022-10-20T08:01:02.424Z]     at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.loadGenerators (ApplicationGeneratorDiscovery.java:62)<br/>[2022-10-20T08:01:02.424Z]     at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.discover (ApplicationGeneratorDiscovery.java:48)<br/>[2022-10-20T08:01:02.424Z]     at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateFiles (KogitoAssetsProcessor.java:262)<br/>[2022-10-20T08:01:02.424Z]     at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateSources (KogitoAssetsProcessor.java:140)<br/>[2022-10-20T08:01:02.424Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2022-10-20T08:01:02.424Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2022-10-20T08:01:02.424Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2022-10-20T08:01:02.424Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2022-10-20T08:01:02.424Z]     at io.quarkus.deployment.ExtensionLoader$3.execute (ExtensionLoader.java:909)<br/>[2022-10-20T08:01:02.424Z]     at io.quarkus.builder.BuildContext.run (BuildContext.java:281)<br/>[2022-10-20T08:01:02.424Z]     at org.jboss.threads.ContextHandler$1.runWith (ContextHandler.java:18)<br/>[2022-10-20T08:01:02.424Z]     at org.jboss.threads.EnhancedQueueExecutor$Task.run (EnhancedQueueExecutor.java:2449)<br/>[2022-10-20T08:01:02.424Z]     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run (EnhancedQueueExecutor.java:1478)<br/>[2022-10-20T08:01:02.424Z]     at java.lang.Thread.run (Thread.java:829)<br/>[2022-10-20T08:01:02.424Z]     at org.jboss.threads.JBossThread.run (JBossThread.java:501)<br/>[2022-10-20T08:01:02.424Z] [ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.13.2.Final:build (default) on project serverless-workflow-testing-with-rest-assured: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	[error]: Build step org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor#generateSources threw an exception: org.kie.kogito.codegen.process.ProcessCodegenException: Duplicated process with id hello found in the project, please review .bpmn files<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at org.kie.kogito.codegen.process.ProcessCodegen.<init>(ProcessCodegen.java:258)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at org.kie.kogito.codegen.process.ProcessCodegen.ofProcesses(ProcessCodegen.java:228)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at org.kie.kogito.codegen.process.ProcessCodegen.ofCollectedResources(ProcessCodegen.java:156)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at org.kie.kogito.codegen.process.ProcessCodegenFactory.create(ProcessCodegenFactory.java:29)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.lambda$loadGenerators$0(ApplicationGeneratorDiscovery.java:60)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.loadGenerators(ApplicationGeneratorDiscovery.java:62)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.discover(ApplicationGeneratorDiscovery.java:48)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateFiles(KogitoAssetsProcessor.java:262)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateSources(KogitoAssetsProcessor.java:140)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)<br/>[2022-10-20T08:01:02.424Z] [ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java [...]

2022-10-20 08:30 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#412` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-examples/412/display/redirect

**Test results:**
- PASSED: 362
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-10-20T08:30:10.333Z]     at org.kie.kogito.codegen.process.ProcessCodegen.<init> (ProcessCodegen.java:258)<br/>[2022-10-20T08:30:10.333Z]     at org.kie.kogito.codegen.process.ProcessCodegen.ofProcesses (ProcessCodegen.java:228)<br/>[2022-10-20T08:30:10.333Z]     at org.kie.kogito.codegen.process.ProcessCodegen.ofCollectedResources (ProcessCodegen.java:156)<br/>[2022-10-20T08:30:10.333Z]     at org.kie.kogito.codegen.process.ProcessCodegenFactory.create (ProcessCodegenFactory.java:29)<br/>[2022-10-20T08:30:10.333Z]     at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.lambda$loadGenerators$0 (ApplicationGeneratorDiscovery.java:60)<br/>[2022-10-20T08:30:10.333Z]     at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:195)<br/>[2022-10-20T08:30:10.333Z]     at java.util.Iterator.forEachRemaining (Iterator.java:133)<br/>[2022-10-20T08:30:10.333Z]     at java.util.Spliterators$IteratorSpliterator.forEachRemaining (Spliterators.java:1801)<br/>[2022-10-20T08:30:10.333Z]     at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:484)<br/>[2022-10-20T08:30:10.333Z]     at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:474)<br/>[2022-10-20T08:30:10.333Z]     at java.util.stream.ReduceOps$ReduceOp.evaluateSequential (ReduceOps.java:913)<br/>[2022-10-20T08:30:10.333Z]     at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)<br/>[2022-10-20T08:30:10.333Z]     at java.util.stream.ReferencePipeline.collect (ReferencePipeline.java:578)<br/>[2022-10-20T08:30:10.333Z]     at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.loadGenerators (ApplicationGeneratorDiscovery.java:62)<br/>[2022-10-20T08:30:10.333Z]     at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.discover (ApplicationGeneratorDiscovery.java:48)<br/>[2022-10-20T08:30:10.333Z]     at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateFiles (KogitoAssetsProcessor.java:262)<br/>[2022-10-20T08:30:10.333Z]     at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateSources (KogitoAssetsProcessor.java:140)<br/>[2022-10-20T08:30:10.333Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2022-10-20T08:30:10.333Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2022-10-20T08:30:10.333Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2022-10-20T08:30:10.333Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2022-10-20T08:30:10.333Z]     at io.quarkus.deployment.ExtensionLoader$3.execute (ExtensionLoader.java:909)<br/>[2022-10-20T08:30:10.333Z]     at io.quarkus.builder.BuildContext.run (BuildContext.java:281)<br/>[2022-10-20T08:30:10.333Z]     at org.jboss.threads.ContextHandler$1.runWith (ContextHandler.java:18)<br/>[2022-10-20T08:30:10.333Z]     at org.jboss.threads.EnhancedQueueExecutor$Task.run (EnhancedQueueExecutor.java:2449)<br/>[2022-10-20T08:30:10.333Z]     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run (EnhancedQueueExecutor.java:1478)<br/>[2022-10-20T08:30:10.333Z]     at java.lang.Thread.run (Thread.java:829)<br/>[2022-10-20T08:30:10.333Z]     at org.jboss.threads.JBossThread.run (JBossThread.java:501)<br/>[2022-10-20T08:30:10.333Z] [ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.13.2.Final:build (default) on project serverless-workflow-testing-with-rest-assured: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/>[2022-10-20T08:30:10.333Z] [ERROR] 	[error]: Build step org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor#generateSources threw an exception: org.kie.kogito.codegen.process.ProcessCodegenException: Duplicated process with id hello found in the project, please review .bpmn files<br/>[2022-10-20T08:30:10.333Z] [ERROR] 	at org.kie.kogito.codegen.process.ProcessCodegen.<init>(ProcessCodegen.java:258)<br/>[2022-10-20T08:30:10.333Z] [ERROR] 	at org.kie.kogito.codegen.process.ProcessCodegen.ofProcesses(ProcessCodegen.java:228)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at org.kie.kogito.codegen.process.ProcessCodegen.ofCollectedResources(ProcessCodegen.java:156)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at org.kie.kogito.codegen.process.ProcessCodegenFactory.create(ProcessCodegenFactory.java:29)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.lambda$loadGenerators$0(ApplicationGeneratorDiscovery.java:60)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.loadGenerators(ApplicationGeneratorDiscovery.java:62)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at org.kie.kogito.codegen.core.utils.ApplicationGeneratorDiscovery.discover(ApplicationGeneratorDiscovery.java:48)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateFiles(KogitoAssetsProcessor.java:262)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateSources(KogitoAssetsProcessor.java:140)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)<br/>[2022-10-20T08:30:10.334Z] [ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java [...]

2022-10-20 14:56 UTC, jstastny-cz commented
Please help me understand the scope, we're changing 2 groups of examples
* quarkus-examples/*
** just adding source-files dependency
* serverless-workflow-examples/*
** adding source-files and devui dependencies to all the examples in this directory.

While I understand that serverless-workflow-devui makes sense just in serverless-workflow-examples, question is why do we need to add the new source-files dependency into quarkus-examples too, the svg rendering has changed also there?

2022-10-20 14:58 UTC, AjayJagan commented
> Please help me understand the scope, we're changing 2 groups of examples
> 
> * quarkus-examples/*
>   
>   * just adding source-files dependency
> * serverless-workflow-examples/*
>   
>   * adding source-files and devui dependencies to all the examples in this directory.
> 
> While I understand that serverless-workflow-devui makes sense just in serverless-workflow-examples, question is why do we need to add the new source-files dependency into quarkus-examples too, the svg rendering has changed also there?

so the graphql query to get the details for both the processes and the serverless workflow are the same. So I had to add the source dependency for serverless workflow, in which case if the quarkus examples miss the source then graphql would throw an error.

2022-10-20 15:11 UTC, jstastny-cz approved these changes
LGTM.

2022-10-20 16:30 UTC, paulovmr approved these changes

2022-10-20 16:36 UTC, paulovmr requested changes
@AjayJagan There is a build error related to the `serverless-workflow-service-calls-quarkus` module. Could you check please?

2022-10-20 19:14 UTC, pefernan approved these changes

2022-10-25 12:41 UTC, paulovmr approved these changes

2022-10-25 12:42 UTC, merged