KOGITO-8303: fix CloudEvent form in DevUi
apache/incubator-kie-examples pull request #1538
Opened 2023-01-18 11:49 UTC by pefernan

Enhanced example to use cloud event to start instad of REST call. Also improved README to show how to run the example on Dev Ui.

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `main` branch!**

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-lts</b>
 
- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [kogito-examples] mandrel</b>

- for <b>mandrel lts checks</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins run mandrel-lts</b>

- for a <b>specific mandrel lts check</b>  
  Run native checks against Mandrel image and quarkus lts branch 
  Please add comment: <b>Jenkins (re)run [kogito-examples] mandrel-lts</b>
 
</details>

2023-01-18 12:10 UTC, fjtirado approved these changes

2023-01-18 12:16 UTC, kie-ci3 commented
**(tests) - kogito-springboot-examples job** `#79` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-springboot-examples/79/display/redirect

**Test results:**
- PASSED: 128
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-springboot-examples/79/testReport/org.kie.kogito.springboot.outbox/OutboxIT/___/">org.kie.kogito.springboot.outbox.OutboxIT.(?)</a></summary>
java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49729] should be listening)<br/>	at org.kie.kogito.springboot.outbox.OutboxIT.before(OutboxIT.java:86)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49729] should be listening)<br/>
</details>

2023-01-18 12:20 UTC, kie-ci3 commented
**(tests) - serverless-workflow-examples job** `#79` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.serverless-workflow-examples/79/display/redirect

**Test results:**
- PASSED: 76
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.serverless-workflow-examples/79/testReport/org.kie.kogito.examples/ConsumingEventsOverHttpIT/testEventOverHttp/">org.kie.kogito.examples.ConsumingEventsOverHttpIT.testEventOverHttp</a></summary>
1 expectation failed.<br/>Expected status code <201> but was <400>.<br/>
</details>

2023-01-18 20:44 UTC, kie-ci3 commented
**(tests) - kogito-quarkus-examples job** `#82` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.kogito-quarkus-examples/82/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2023-01-18T20:41:58.357Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-quarkus-examples # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.38.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 71b424114186f99606bbbf3ca420df83f67c84c8 # timeout=10<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-01-18T20:41:59.104Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2023-01-18T20:41:59.132Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2023-01-18T20:41:59.713Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-examples.tests.kogito-quarkus-examples<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-01-18T20:41:59.751Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2023-01-18T20:42:00.057Z] + df -h<br/>[2023-01-18T20:42:00.058Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2023-01-18T20:42:00.058Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2023-01-18T20:42:00.058Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2023-01-18T20:42:00.058Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2023-01-18T20:42:00.058Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2023-01-18T20:42:00.058Z] /dev/vda1        80G   26G   55G  32% /<br/>[2023-01-18T20:42:00.058Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2023-01-18T20:42:00.081Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2023-01-18T20:42:00.360Z] + du -h -d1 /home/jenkins<br/>[2023-01-18T20:42:00.360Z] 8.0K	/home/jenkins/.ssh<br/>[2023-01-18T20:42:00.360Z] 0	/home/jenkins/go<br/>[2023-01-18T20:42:00.360Z] 8.0K	/home/jenkins/.vnc<br/>[2023-01-18T20:42:00.360Z] 5.9G	/home/jenkins/.m2<br/>[2023-01-18T20:42:00.360Z] 2.2G	/home/jenkins/git-repos<br/>[2023-01-18T20:42:00.360Z] 8.0K	/home/jenkins/.config<br/>[2023-01-18T20:42:00.360Z] 4.0K	/home/jenkins/.cekit<br/>[2023-01-18T20:42:00.614Z] 69M	/home/jenkins/virtenvs<br/>[2023-01-18T20:42:00.614Z] 185M	/home/jenkins/remoting<br/>[2023-01-18T20:42:00.614Z] 0	/home/jenkins/.cache<br/>[2023-01-18T20:42:00.614Z] 0	/home/jenkins/caches<br/>[2023-01-18T20:42:00.614Z] 3.6M	/home/jenkins/workspace<br/>[2023-01-18T20:42:00.614Z] 0	/home/jenkins/.pki<br/>[2023-01-18T20:42:00.614Z] 139M	/home/jenkins/tools<br/>[2023-01-18T20:42:00.614Z] 27M	/home/jenkins/.npm<br/>[2023-01-18T20:42:00.614Z] 8.4G	/home/jenkins<br/>[Pipeline] echo<br/>[2023-01-18T20:42:00.636Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2023-01-18T20:42:00.913Z] + du -h -d3 /home/jenkins/workspace<br/>[2023-01-18T20:42:00.914Z] 4.0K	/home/jenkins/workspace/Tools/properties-generator<br/>[2023-01-18T20:42:00.914Z] 0	/home/jenkins/workspace/Tools/properties-generator@tmp<br/>[2023-01-18T20:42:00.914Z] 4.0K	/home/jenkins/workspace/Tools<br/>[2023-01-18T20:42:00.914Z] 0	/home/jenkins/workspace/PROD<br/>[2023-01-18T20:42:00.914Z] 3.5M	/home/jenkins/workspace/KIE/kogito/main<br/>[2023-01-18T20:42:00.914Z] 3.5M	/home/jenkins/workspace/KIE/kogito<br/>[2023-01-18T20:42:00.914Z] 0	/home/jenkins/workspace/KIE/7.67.x/deployedRep<br/>[2023-01-18T20:42:00.914Z] 0	/home/jenkins/workspace/KIE/7.67.x<br/>[2023-01-18T20:42:00.914Z] 3.5M	/home/jenkins/workspace/KIE<br/>[2023-01-18T20:42:00.914Z] 3.6M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-01-18T20:42:01.315Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2023-01-18T20:42:01.398Z] [INFO] build-chain version recovered '2.3.36'<br/>[Pipeline] sh<br/>[2023-01-18T20:42:01.679Z] + npm install -g @kie/build-chain-action@2.3.36 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2023-01-18T20:42:03.559Z] npm WARN ERESOLVE overriding peer dependency<br/>[2023-01-18T20:42:03.559Z] npm WARN Found: @octokit/core@2.5.4<br/>[2023-01-18T20:42:03.559Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/core<br/>[2023-01-18T20:42:03.559Z] npm WARN   @octokit/core@"^2.4.3" from @octokit/rest@17.11.2<br/>[2023-01-18T20:42:03.559Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2023-01-18T20:42:03.559Z] npm WARN     @octokit/rest@"^17.6.0" from @kie/build-chain-action@2.3.36<br/>[2023-01-18T20:42:03.559Z] npm WARN     node_modules/@kie/build-chain-action<br/>[2023-01-18T20:42:03.559Z] npm WARN   1 more (@octokit/plugin-paginate-rest)<br/>[2023-01-18T20:42:03.559Z] npm WARN <br/>[2023-01-18T20:42:03.559Z] npm WARN Could not resolve dependency:<br/>[2023-01-18T20:42:03.559Z] npm WARN peer @octokit/core@">=3" from @octokit/plugin-request-log@1.0.4<br/>[2023-01-18T20:42:03.559Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/plugin-request-log<br/>[2023-01-18T20:42:03.559Z] npm WARN   @octokit/plugin-request-log@"^1.0.0" from @octokit/rest@17.11.2<br/>[2023-01-18T20:42:03.559Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2023-01-18T20:42:04.486Z] <br/>[2023-01-18T20:42:04.486Z] changed 110 packages, and audited 111 packages in 3s<br/>[2023-01-18T20:42:04.486Z] <br/>[2023-01-18T20:42:04.486Z] 5 packages are looking for funding<br/>[2023-01-18T20:42:04.486Z]   run `npm fund` for details<br/>[2023-01-18T20:42:04.486Z] <br/>[2023-01-18T20:42:04.486Z] found 0 vulnerabilities<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus)<br/>Stage "Build quarkus" skipped due to when conditional<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build quarkus platform)<br/>Stage "Build quarkus platform" skipped due to when conditio [...]

2023-01-18 21:10 UTC, kie-ci3 commented
**(tests) - serverless-workflow-examples job** `#81` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.serverless-workflow-examples/81/display/redirect

**Test results:**
- PASSED: 75
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-examples.tests.serverless-workflow-examples/81/testReport/org.kie.kogito.examples/AnnotationsAndDescriptionsTest/testAnnotations(String,_String)[1]/">org.kie.kogito.examples.AnnotationsAndDescriptionsTest.testAnnotations(String, String)[1]</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor#setupKubernetesDevService threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/> at io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor.setupKubernetesDevService(DevServicesKubernetesProcessor.java:119)<br/> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:281)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)<br/> at java.base/java.lang.Thread.run(Thread.java:829)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:501)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor.lambda$startKubernetes$7(DevServicesKubernetesProcessor.java:227)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:369)<br/> at io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor.startKubernetes(DevServicesKubernetesProcessor.java:241)<br/> at io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor.setupKubernetesDevService(DevServicesKubernetesProcessor.java:109)<br/> ... 11 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 17 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at com.dajudge.kindcontainer.ApiServerContainer.containerIsStarting(ApiServerContainer.java:142)<br/> at org.testcontainers.containers.GenericContainer.containerIsStarting(GenericContainer.java:692)<br/> at com.dajudge.kindcontainer.KubernetesContainer.containerIsStarting(KubernetesContainer.java:151)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:474)<br/> ... 19 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)<br/> ... 24 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 25 more<br/>Caused by: com.github.dockerjava.api.exception.ConflictException: Status 409: {"message":"cannot join network of a non running container: 73613b104d0a19488660d3552f193f33fa5769cf63350fcab26189d22b9187b9"}<br/><br/> at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:245)<br/> at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)<br/> at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)<br/> at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)<br/> at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)<br/> at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)<br/> at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:441)<br/> ... 27 more<br/>
</details>

2023-01-25 20:35 UTC, paulovmr requested changes

2023-01-25 20:35 UTC, paulovmr commented on serverless-workflow-examples/serverless-workflow-consuming-events-over-http-quarkus/README.md
> +The service based on the JSON workflow definition can be started by publishing an HTTP event request to 'http://localhost:8080/startevent'
Looks like this part is duplicated with a few changes.

2023-01-27 13:25 UTC, paulovmr approved these changes

2023-05-08 20:32 UTC, pefernan commented
@paulovmr @fjtirado I see this was still open, just fetched latest and fixed conflicts... I think it would be good to have it in :D

2023-05-12 11:34 UTC, merged