DRAFT: Begin work on the Quarkus version of the spring-boot flight example.
apache/incubator-kie-examples pull request #157
Opened 2020-03-20 19:38 UTC by Christopher-Chianelli

TODO:
- Fix frontend styling (how did that break when only the backend changed?)
- Update README
- Fix process test

2020-03-21 07:54 UTC, ge0ffrey commented on jbpm-optaplanner-quarkus-example/.gitignore
> +/jbpm-gwt/
Let's remove these 4 lines.

2020-03-21 07:54 UTC, ge0ffrey commented on jbpm-optaplanner-quarkus-example/.gitignore
> +db-settings.xml
Let's remove these 3 lines

2020-03-21 07:54 UTC, ge0ffrey commented on jbpm-optaplanner-quarkus-example/.gitignore
> +*.tlog
Let's remove these 5 lines

2020-03-21 08:01 UTC, ge0ffrey commented on jbpm-optaplanner-quarkus-example/.gitignore
> +*.tlog
Actually, non of the other examples in this repo have a .gitignore file, let's remove this file entirely.

There are basically 2 ways to deal with .gitignore:
A) a single root .gitignore file that says to exclude all "target" and ".idea" directories, in any subdirectory.
B) a .gitingore file per module tot exclude "/target" in this directory only.

Pro/con: B) is more work, but A) is more error prone (think java package org.foo.target.goal)

This repository is employing tactic A), so this PR should adhere to that and not have a .gitignore file here.

2020-03-21 08:01 UTC, ge0ffrey commented on jbpm-optaplanner-quarkus-example/README.md
> +# jBPM + OptaPlanner + SpringBoot example
do a "find in directory" for "spring" :)

2020-03-21 08:02 UTC, ge0ffrey commented on jbpm-optaplanner-quarkus-example/README.md
> +You can take a look at the [swagger definition](http://localhost:8080/swagger.json) - automatically generated and included in this service - to determine all available operations exposed by this serv
Does the quarkus version support swagger too?

"You can take a look at ..." -> "Take a look at ..."

2020-03-21 08:05 UTC, ge0ffrey commented on jbpm-optaplanner-quarkus-example/pom.xml
> +        <version>8.0</version>
This dependency is wierd.
In a quarkus world, depending on the quakus extensions alone should be enough. Can we remove this dependency?

2020-03-21 08:07 UTC, ge0ffrey commented on jbpm-optaplanner-quarkus-example/pom.xml
> +        <version>0.37</version>
The optaplanner-quickstart for quarkus doesn't have this dependency, because we couldn't get that to work.
1) Do a diff between this pom and the optaplanner-quickstart pom to verify there is nothing in here that you don't need
2) If you can get the locator to work, such as the js file urls don't have a version number, that would be great (out of scope for this PR to get it merged asap I would argue) and then we'd like to consider that for the optaplanner-quickstart example too :) I do suspect that's just a missing feature of quarkus...

2020-03-21 08:09 UTC, ge0ffrey commented on jbpm-optaplanner-quarkus-example/pom.xml
> +    </dependency>
Move this quarkus-optaplanner-jackson directly under the optaplanner one, it's easier to read. (Code is read 10 times more than it is written, so readability matters).

2020-03-21 08:09 UTC, ge0ffrey commented on jbpm-optaplanner-quarkus-example/pom.xml
> +    </dependency>
Can we remove this one?

2020-03-21 08:10 UTC, ge0ffrey commented on jbpm-optaplanner-quarkus-example/pom.xml
> +      </plugin> -->
Not needed, remove these 4 lines.

Btw: any comment here, please also check the springboot example for that and if it applies there too (and it's not exceptionally different like the webjar locator which is supported there) then adjust it there too please. So if this commented out code is there, remove it please there too.

2020-03-21 08:11 UTC, ge0ffrey commented on jbpm-optaplanner-quarkus-example/pom.xml
> +        <artifactId>swagger-maven-plugin</artifactId>
Does this work with Quarkus? :)

2020-03-21 08:13 UTC, ge0ffrey commented on jbpm-optaplanner-quarkus-example/src/main/java/org/kie/kogito/examples/domain/Seat.java
> +    }
Are business intelligent equals/hashCode methods needed for the quarkus and spring boot example to work?
Less is more: if it works without these methods on the domain objects, please remove them, otherwise users think they are crucial.

2020-03-21 08:15 UTC, ge0ffrey commented on jbpm-optaplanner-quarkus-example/src/main/java/org/kie/kogito/examples/service/FlightSeatingSolveService.java
> +        }).start();
Oh yes, I need to prioritize PLANNER-1868 so there's no need to do "new Thread". Let's merge this as is and feel free to remind me about 1868 if I haven't fixed that next week.

2020-03-21 08:16 UTC, ge0ffrey commented on jbpm-optaplanner-quarkus-example/src/main/java/org/kie/kogito/examples/solver/FlightSeatingConstraintProvider.java
> +                    return (int) Math.round(Point2D.distance(0, 0, averageX, averageY) * passengerCount * 100);
we might want to do this in "milis" or maybe not. Something to discuss, please bring this subject up in our next sync-up so I can explain the "milis" approach and we can determine if it's needed here.

2020-03-21 08:17 UTC, ge0ffrey commented on jbpm-optaplanner-quarkus-example/src/main/resources/META-INF/resources/index.html
> +    <title>OptaPlanner Spring Boot example</title>
ctrl-shift-f is your friend :)

2020-03-21 08:18 UTC, ge0ffrey commented on pom.xml
> +    <module>jbpm-optaplanner-quarkus-example</module>
Quarkus First :) Please move this line one line up.

2020-03-23 13:07 UTC, Christopher-Chianelli commented on jbpm-optaplanner-quarkus-example/pom.xml
> +        <version>8.0</version>
Just tested, we can; unrelated, IDE cannot find Optaplanner, talks about missing dependency version for the OptaPlanner extensions; it compiles and runs fine though.

2020-03-23 13:13 UTC, Christopher-Chianelli commented on jbpm-optaplanner-quarkus-example/pom.xml
> +        <artifactId>swagger-maven-plugin</artifactId>
Nope, got a JSON with only title and version after changing the location. Removing.

2020-03-23 13:22 UTC, Christopher-Chianelli commented on jbpm-optaplanner-quarkus-example/src/main/java/org/kie/kogito/examples/domain/Seat.java
> +    }
Not needed; @triceo advocated for it since `Seat` is immutable. Curious, how does OptaPlanner handles `equals` but not `is` (that is, `x.equals(y)` but not `x == y`)? If I pin a passenger to a Seat that is not a Seat on the Flight, but rather a Seat equal to a Seat on the Flight, will there be no adverse side effects (the Seat won't be in a Problem Fact Collection)?

2020-03-23 13:24 UTC, Christopher-Chianelli commented on jbpm-optaplanner-quarkus-example/src/main/java/org/kie/kogito/examples/domain/Seat.java
> +    }
(If it handled well,
```
            String[] seatLoc = passenger.getSeat().split(";");
            int row = Integer.parseInt(seatLoc[0]);
            int col = Integer.parseInt(seatLoc[1]);
            seat = flight.getSeatList().stream().filter(s -> s.getRow() == row && s.getColumn() == col).findAny().get();
```
can be removed and we can just access the Seat directly from the DTO.

2020-03-23 15:56 UTC, Christopher-Chianelli commented on jbpm-optaplanner-quarkus-example/README.md
> +You can take a look at the [swagger definition](http://localhost:8080/swagger.json) - automatically generated and included in this service - to determine all available operations exposed by this serv
`jbpm-quarkus-example/README.md ` also mentions Swagger, but doesn't have Swagger in the `pom.xml` (nor anything swagger related in resources)

2020-03-23 16:04 UTC, Christopher-Chianelli commented on jbpm-optaplanner-quarkus-example/pom.xml
> +    </dependency>
Previous reasoning was to have all jackson modules grouped together (there are three: quarkus-jackson, resteasy-jackson, and optaplanner-jackson); moved it under optaplanner.

2020-03-23 16:05 UTC, Christopher-Chianelli commented on jbpm-optaplanner-quarkus-example/pom.xml
> +      </plugin> -->
Not there; this code is needed for spring boot, but not for Quarkus.

2020-03-23 18:06 UTC, Christopher-Chianelli commented on jbpm-optaplanner-quarkus-example/pom.xml
> +        <version>0.37</version>
I doubt we can get the locator to work due to how webjars work in Quarkus. Quarkus put webjars in `target/lib` and reference them in the `META-INF/MANIFEST.MF`'s `Class-Path`.

Meanwhile, Spring Boot put the webjars directly in `BOOT-INF/lib/`. 

From what I see in `Spring`, `Spring` doesn't actually use the `webjar-locator`, but rather use its existance as a trigger to server versionless resources instead of versioned resources via https://github.com/spring-projects/spring-boot/blob/7f509bf84e9b51416ce65a777a3b5b2521921a6f/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration.java#L299-L317

2020-03-23 18:16 UTC, Christopher-Chianelli commented on jbpm-optaplanner-quarkus-example/pom.xml
> +        <version>0.37</version>
(the condition: https://github.com/spring-projects/spring-boot/blob/aef92b9295f62d008faa9ab79905a474bf3496f3/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/OnEnabledResourceChainCondition.java)

and the customizer:

https://github.com/spring-projects/spring-boot/blob/7f509bf84e9b51416ce65a777a3b5b2521921a6f/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration.java#L519-L557

2020-03-23 19:02 UTC, Christopher-Chianelli commented on jbpm-optaplanner-quarkus-example/pom.xml
> +        <version>0.37</version>
My guess is we can either add a new quarkus extension for this or add the functionality to the resteasy extension.

2020-03-26 12:21 UTC, ge0ffrey commented on jbpm-optaplanner-quarkus-example/src/main/java/org/kie/kogito/examples/domain/Seat.java
> +    }
OptaPlanner expects that given the following input:
```
- Rooms [A, B]
- Lessons [ {Math, room: A}, {French, room: A}]
```
that all those A instances are the same instance. (That's btw that in JPA the rooms and lessons need to be fetched in the same transaction).

Then, the output of OptaPlanner also respects this philosophy. Basically, a solution will never have 2 room A instances. Or two seat instances. (Even if planning cloning happens that still holds true) So default Object.hashCode/equals() suffices. Less code is better than more code.

2020-03-26 12:24 UTC, ge0ffrey commented on jbpm-optaplanner-quarkus-example/pom.xml
> +        <version>0.37</version>
Great work on building that new quarkus extension. This PR can't wait for the quarkus 1.4 release (which hopefully has the webjar extension), so +1 to workaround it for now. Do create a jira to remove that workaround in this example once quarkus 1.4 is released.

2020-03-26 12:25 UTC, ge0ffrey approved these changes

2020-04-09 19:31 UTC, ricardozanini commented
Is this still a draft?

2020-04-09 19:36 UTC, Christopher-Chianelli commented
@ricardozanini I still need to implement a test, so yes (I needed to work on an urgent task this sprint, leading most of my PR's abandoned for the past 3 weeks, going back to finish them now)

2020-04-16 21:27 UTC, Christopher-Chianelli commented
@ricardozanini added test for both jvm and native mode; removed draft status

2020-04-22 13:09 UTC, ge0ffrey commented
jenkins retest this

2020-04-22 13:21 UTC, evacchi reviewed
I think it looks good, but I think you'll have to verify the Quarkus dependency and/or rebase on master, since the build is currently red.

2020-04-22 13:21 UTC, evacchi commented on process-optaplanner-quarkus/README.md
> +### Prerequisites
align prerequisites to the rest of the repo (java 11, maven 3.6.x)

2020-04-22 13:22 UTC, evacchi commented on jbpm-optaplanner-quarkus-example/README.md
> +You can take a look at the [swagger definition](http://localhost:8080/swagger.json) - automatically generated and included in this service - to determine all available operations exposed by this serv
you have to add the OpenAPI Quarkus extension. You can also set it to always enabled (otherwise it's only available in devmode)

2020-04-23 19:24 UTC, ricardozanini requested changes
Hi @Christopher-Chianelli !
Thanks for this example, but please consider also adding an example for the operator deployment on `operator` directory. For reference, see the OptaPlanner springboot example.

2020-04-23 19:24 UTC, ricardozanini commented on process-optaplanner-quarkus/README.md
> +# jBPM + OptaPlanner + Quarkus example
```suggestion
# Process + OptaPlanner + Quarkus example
```

2020-04-23 19:24 UTC, ricardozanini commented on process-optaplanner-quarkus/pom.xml
> +  <name>Kogito Example :: jBPM, OptaPlanner and Quarkus</name>
```suggestion
  <name>Kogito Example :: Process, OptaPlanner and Quarkus</name>
```

Please also look up after this word in the README and any docs in this example.

2020-04-23 19:56 UTC, Christopher-Chianelli commented
@ricardozanini Done (I think; don't know how to test locally)

2020-04-24 14:31 UTC, ricardozanini approved these changes

2020-04-30 13:02 UTC, evacchi approved these changes
if anything from others have been addressed this is good for me

2020-04-30 13:03 UTC, merged