[1.13.x-blue][BXMSPROD-2057] Updating references to the new kie-ci actions folder
apache/incubator-kie-examples pull request #1686
Opened 2023-06-12 08:48 UTC by bacciotti

2023-06-13 05:34 UTC, Ginxo approved these changes
LGTM

2023-06-13 05:35 UTC, Ginxo requested changes
please check

2023-06-13 05:35 UTC, Ginxo commented on .github/workflows/kogito-examples-pr.yml
> +        uses: kiegroup/kie-ci/.ci/actions/build-chain@1.13.x
definition-file not defined here

2023-06-15 07:33 UTC, lampajr requested changes

2023-06-15 07:33 UTC, lampajr commented on .github/workflows/kogito-examples-pr.yml
> +        uses: kiegroup/kie-ci/.ci/actions/ubuntu-disk-space@1.13.x
`1.13.x` branch does not exist on `kie-ci` repo, we should change to `main` as already done on other repos :)

2023-06-15 09:24 UTC, lampajr approved these changes

2023-06-19 07:49 UTC, Ginxo requested changes
please check

2023-06-19 07:49 UTC, Ginxo commented on .github/workflows/kogito-examples-pr.yml
> +          definition-file: https://raw.githubusercontent.com/${GROUP:kiegroup}/kogito-pipelines/${BRANCH:main}/.ci/pull-request-config.yaml
is it main as default or 1.13.x?

2023-06-20 07:38 UTC, bacciotti commented on .github/workflows/kogito-examples-pr.yml
> +          definition-file: https://raw.githubusercontent.com/${GROUP:kiegroup}/kogito-pipelines/${BRANCH:main}/.ci/pull-request-config.yaml
@Ginxo IIUC it is taking 1.13.x.

2023-06-20 08:24 UTC, Ginxo approved these changes
LGTM

2023-06-20 08:24 UTC, Ginxo commented
please merge once undrafted

2023-06-20 08:51 UTC, merged