KOGITO-1544: Move kogito-travel-agency-tutorial to kogito-examples
apache/incubator-kie-examples pull request #178
Opened 2020-04-02 08:10 UTC by evacchi

supersedes #177

I haven't added this to the main pom.xml yet. We can do this here or in a next PR. 
I would go with starting with merging and then do further changes later.
We are bringing in only the old '06'. But commit a106b74 can be always restored if we want to bring back 01. We can also bring back 02,03,04,06 with commit 5b9d343 

**[PLEASE DON'T SQUASH](https://www.youtube.com/watch?v=YIAnkrPgTvY)**

2020-04-02 13:52 UTC, ricardozanini commented
Please wait for this to be merged: https://github.com/kiegroup/kogito-examples/pull/168

2020-04-02 13:55 UTC, ricardozanini requested changes
Awesome! Just small comments. So we will keep only the "latest" version in this repo? The old one will be removed?

2020-04-02 13:55 UTC, ricardozanini commented on travel-agency/kogito-travel-agency/pom.xml
> +    <kogito.version>0.8.1</kogito.version>
We might want to inherit this from examples BOM?

2020-04-02 13:55 UTC, ricardozanini commented on travel-agency/kogito-visas/pom.xml
> +    <kogito.version>0.8.1</kogito.version>
Same here regarding the examples BOM inheritance

2020-04-02 14:27 UTC, radtriste approved these changes
> We are bringing in only the old '06'

08 you mean now ? :)
I would  rename the inner folders to `travel-agency` and `visas` ?

All other comments should be addressed in further PR but I let them here as it is easier.

2020-04-02 14:27 UTC, radtriste commented on travel-agency/kogito-travel-agency/README.md
> +  - Java 1.8.0+ installed
Java 11

2020-04-02 14:27 UTC, radtriste commented on travel-agency/kogito-travel-agency/README.md
> +  - GraalVM installed
19.3.1+

2020-04-02 14:27 UTC, radtriste commented on travel-agency/.gitignore
> +bin/
do we need the .gitignore here ?

2020-04-02 14:27 UTC, radtriste commented on travel-agency/README.md
> +[Base travel agency service with persistence](02-kogito-travel-agency) - deals with all the basic steps to book flight and hotel.
?? should be 08 or ?

2020-04-02 14:27 UTC, radtriste commented on travel-agency/kogito-travel-agency/.gitignore
> +bin/
we may delete that file .the root one should be enough

2020-04-02 14:27 UTC, radtriste commented on travel-agency/kogito-visas/README.md
> +  - Java 1.8.0+ installed
java 11

2020-04-02 14:27 UTC, radtriste commented on travel-agency/kogito-visas/README.md
> +  - GraalVM installed
19.3.1+

2020-04-02 14:27 UTC, radtriste commented on travel-agency/kogito-travel-agency/README.md
> +You can install Infinispan server by downloading it from [official website](https://infinispan.org/download) version to be used in 10.0.0.CR1
I would check the Infinispan minimum version

2020-04-02 14:27 UTC, radtriste commented on travel-agency/kogito-visas/.gitignore
> +bin/
we may delete that file .the root one should be enough

2020-04-02 14:27 UTC, radtriste commented on travel-agency/kogito-visas/README.md
> +You can install Infinispan server by downloading it from [official website](https://infinispan.org/download) version to be used in 10.0.0.CR1
Infinispan minimum version

2020-04-02 14:27 UTC, radtriste commented on travel-agency/kogito-visas/README.md
> +It can be downloaded from [Kogito Data Index Service 0.8.0](http://repo2.maven.org/maven2/org/kie/kogito/data-index-service/0.4.0/data-index-service-0.4.0-runner.jar)
Change link to point to 0.8.0

2020-04-02 14:27 UTC, radtriste commented on travel-agency-example/.gitignore
> +bin/
we may delete that file .the root one should be enough

2020-04-02 14:27 UTC, radtriste commented on travel-agency-example/README.md
> +[Base travel agency service](01-kogito-travel-agency) - deals with all the basic steps to book flight and hotel.
This link won't work

2020-04-02 14:27 UTC, radtriste commented on travel-agency-example/README.md
> +[Base travel agency service with persistence](02-kogito-travel-agency) - deals with all the basic steps to book flight and hotel.
This one neither

2020-04-02 14:27 UTC, radtriste commented on travel-agency-example/kogito-travel-agency/.gitignore
> +bin/
we may delete that file .the root one should be enough

2020-04-02 14:27 UTC, radtriste commented on travel-agency-example/kogito-travel-agency/README.md
> +  - Java 1.8.0+ installed
Java 11

2020-04-02 14:27 UTC, radtriste commented on travel-agency-example/kogito-travel-agency/README.md
> +  - GraalVM installed
19.3.1+

2020-04-02 14:27 UTC, radtriste commented on travel-agency-example/kogito-travel-agency/README.md
> +You can install Infinispan server by downloading it from [official website](https://infinispan.org/download) version to be used in 10.0.0.CR1
I would check the Infinispan min version ?

2020-04-02 14:27 UTC, radtriste commented on travel-agency-example/kogito-visas/.gitignore
> +bin/
we may delete that file .the root one should be enough

2020-04-02 14:27 UTC, radtriste commented on travel-agency-example/kogito-visas/README.md
> +  - Java 1.8.0+ installed
Java 11

2020-04-02 14:27 UTC, radtriste commented on travel-agency-example/kogito-visas/README.md
> +  - GraalVM installed
19.3.1+

2020-04-02 14:27 UTC, radtriste commented on travel-agency-example/kogito-visas/README.md
> +You can install Infinispan server by downloading it from [official website](https://infinispan.org/download) version to be used in 10.0.0.CR1
Infinispan min version to check

2020-04-02 14:27 UTC, radtriste commented on travel-agency-example/kogito-visas/README.md
> +It can be downloaded from [Kogito Data Index Service 0.8.0](http://repo2.maven.org/maven2/org/kie/kogito/data-index-service/0.4.0/data-index-service-0.4.0-runner.jar)
Link here should be corrected to point to data-index 0.8.0 jar

2020-04-02 18:39 UTC, ricardozanini approved these changes

2020-04-03 06:06 UTC, cristianonicolai approved these changes
@evacchi I added some minor comments and I ḿ fine to leave any chages like renaming modules etc to a follow up pr

2020-04-03 06:06 UTC, cristianonicolai commented on travel-agency-example/.gitignore
> +bin/
+1

2020-04-03 06:06 UTC, cristianonicolai commented on pom.xml
> +    <module>travel-agency-example</module>
based on recent conversation, should it be _kogito-travel-agency_ ? should we drop the _-example_ sounds unnecessary, as we're in the _kogito-examples_ repo :)

2020-04-03 06:06 UTC, cristianonicolai commented on pom.xml
> +    <module>travel-agency-example</module>
This probably conflicts with the submodule name, so yould rename that one to _kogito-travels_.

2020-04-03 06:06 UTC, cristianonicolai commented on travel-agency-example/kogito-visas/.gitignore
> +bin/
+1

2020-04-03 06:06 UTC, cristianonicolai commented on travel-agency-example/kogito-visas/README.md
> +It can be downloaded from [Kogito Data Index Service 0.8.0](http://repo2.maven.org/maven2/org/kie/kogito/data-index-service/0.4.0/data-index-service-0.4.0-runner.jar)
This will keep changing... we either integrate with the project.version or point users to _http://repo2.maven.org/maven2/org/kie/kogito/data-index-service/_ ?

2020-04-03 09:01 UTC, DuncanDoyle commented
The version in this PR seems to be the 06. I've added new features to the 08, and some fixes as well. Any reason we're not using the 08 version in this PR ... It would mean that I need to redo all that work ....

2020-04-03 09:04 UTC, DuncanDoyle approved these changes

2020-04-03 09:05 UTC, radtriste commented
@DuncanDoyle sure about that ? 
we have the `Start management console` into the travel-agency README which is not in 06 ...

2020-04-03 09:13 UTC, evacchi commented on travel-agency/kogito-visas/README.md
> +You can install Infinispan server by downloading it from [official website](https://infinispan.org/download) version to be used in 10.0.0.CR1
asking @tiagodolphine and @cristianonicolai

2020-04-03 09:16 UTC, evacchi commented on travel-agency-example/kogito-visas/README.md
> +It can be downloaded from [Kogito Data Index Service 0.8.0](http://repo2.maven.org/maven2/org/kie/kogito/data-index-service/0.4.0/data-index-service-0.4.0-runner.jar)
let's do https://search.maven.org/artifact/org.kie.kogito/data-index

2020-04-03 10:22 UTC, evacchi commented
@ricardozanini @tiagodolphine do you think we may add instructions to use Docker for the data index instead of the jar? I think it would make sense.

2020-04-03 10:24 UTC, evacchi commented
once it's all done I will squash the last couple of commits so that my commits are just 2-3

2020-04-03 15:40 UTC, ricardozanini commented
> @ricardozanini @tiagodolphine do you think we may add instructions to use Docker for the data index instead of the jar? I think it would make sense.

I've seen a docker compose made by @DuncanDoyle in this repo. Wouldn't be this use case?

2020-04-03 15:42 UTC, evacchi commented
@ricardozanini that does not contain the data-index, only kafka and infinispan AFAIR

2020-04-03 20:52 UTC, ricardozanini commented
> @ricardozanini that does not contain the data-index, only kafka and infinispan AFAIR

It could :thinking:

2020-04-04 08:41 UTC, evacchi commented
this is all green, merging.

2020-04-04 09:31 UTC, evacchi commented
had to fix 1000 conflicts to rebase to retain history, @radtriste or @MarianMacik can you double check? I think it's good to go

2020-04-06 09:18 UTC, merged

2020-04-06 09:58 UTC, MarianMacik reviewed
Just few things. Probably good to address in the future PRs.

There is also a class called `Bla.java` which is probably not necessary?

2020-04-06 09:58 UTC, MarianMacik commented on kogito-travel-agency/README.md
> +and to start any any place.
I guess this no longer holds as we have just one version here.

2020-04-06 09:58 UTC, MarianMacik commented on kogito-travel-agency/docker-compose/prometheus/prometheus-macos-windows.yml
> +    #   password: 'kieserver1!'
This is referencing kieserver.

2020-04-06 18:12 UTC, radtriste commented
@evacchi do you plan any cherry-pick on 0.9.x branch ?