incubator-kie-issues#723: Adding `process-usertasks-timer-data-index-persistence-addon-quarkus` showcasing the `kogito-addons-quarkus-data-index-persistence-postgresql` including Jobs Service
apache/incubator-kie-examples pull request #1833
Opened 2023-11-24 15:37 UTC by pefernan

https://github.com/apache/incubator-kie-issues/issues/723

This PR includes the new `process-usertasks-timer-data-index-persistence-addon-quarkus` showcasing the `kogito-addons-quarkus-data-index-persistence-postgresql` and including Jobs Service.

The README.md isn't finished yet... it's blocked by another issue. 

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `main` branch!**

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [kogito-examples] quarkus-lts</b>
 
- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-examples] native</b>

- for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch 
  Please add comment: <b>Jenkins (re)run [kogito-examples] native-lts</b>
 
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

2023-11-24 18:18 UTC, kie-ci3 commented
**PR job** `#1` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/1833 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1833/1/display/redirect

**Test results:**
- PASSED: 376
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1833/1/testReport/org.kie.kogito.hr/HiringProcessIT/testCandidateNotMeetingRequirements/">org.kie.kogito.hr.HiringProcessIT.testCandidateNotMeetingRequirements</a></summary>
expected: <1> but was: <5>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1833/1/testReport/org.kie.kogito.hr/HiringProcessIT/PR_check___Build_projects___testApprovalProcess/">PR check / Build projects / org.kie.kogito.hr.HiringProcessIT.testApprovalProcess</a></summary>
expected: <1> but was: <5>
</details>

2023-11-27 13:21 UTC, kie-ci3 commented
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/1833 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1833/3/display/redirect

**Test results:**
- PASSED: 371
- FAILED: 4

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1833/3/testReport/org.kie.kogito.hr/HiringProcessIT/testCandidateNotMeetingRequirements/">org.kie.kogito.hr.HiringProcessIT.testCandidateNotMeetingRequirements</a></summary>
expected: <1> but was: <5>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1833/3/testReport/org.kie.kogito.hr/HiringProcessIT/PR_check___Build_projects___testApprovalProcess/">PR check / Build projects / org.kie.kogito.hr.HiringProcessIT.testApprovalProcess</a></summary>
expected: <1> but was: <5>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1833/3/testReport/org.kie.kogito.examples/DataIndexRestIT/testDataIndexRest/">org.kie.kogito.examples.DataIndexRestIT.testDataIndexRest</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/> at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:247)<br/> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:281)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)<br/> at java.base/java.lang.Thread.run(Thread.java:829)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:501)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:372)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:369)<br/> at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:397)<br/> at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:195)<br/> ... 11 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)<br/> ... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)<br/> at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/> ... 17 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Keycloak.*started.*'<br/> at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)<br/> at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)<br/> at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:953)<br/> at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:485)<br/> ... 19 more<br/>
</details>
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-1833/3/testReport/org.acme/AcmeExchangeResourceIT/unauthorizedTest/">org.acme.AcmeExchangeResourceIT.unauthorizedTest</a></summary>
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/> [error]: Build step io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor#startKeycloakContainer threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/> at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:247)<br/> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/> at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/> at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)<br/> at io.quarkus.builder.BuildContext.run(BuildContext.java:281)<br/> at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/> at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)<br/> at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)<br/> at java.base/java.lang.Thread.run(Thread.java:829)<br/> at org.jboss.threads.JBossThread.run(JBossThread.java:501)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/> at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)<br/> at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/> at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.lambda$startContainer$4(KeycloakDevServicesProcessor.java:372)<br/> at java.base/java.util.Optional.orElseGet(Optional.java:369)<br/> at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startContainer(KeycloakDevServicesProcessor.java:397)<br/> at io.quarkus.oidc.deployment.devservices.keycloak.KeycloakDevServicesProcessor.startKeycloakContainer(KeycloakDevServicesProcessor.java:195)<br/> ... 11 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/> at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/> at org.testcontaine [...]

2023-12-01 08:41 UTC, elguardian requested changes
Overall looks good to me. Just need some clarification with the errors.

2023-12-01 08:41 UTC, elguardian commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/README.md
> +interviews until it gets hired.
"until he gets hired."

2023-12-01 08:41 UTC, elguardian commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/README.md
> +*Kogito runtime* directly persist into the *Data-Index* Database simplifying the communication of both services by removing
persist into the database the "Data-Index", simplifying the communication among services removing the need...

2023-12-01 08:41 UTC, elguardian commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/README.md
> +The Development Mode will embed all the needed Infrastructure Services (PostgreSQL, Data-Index & Jobs Service) and wont
won't

2023-12-01 08:41 UTC, elguardian commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/README.md
> +you can run the same `startServices.sh` script but passing the `example` argument
you can run the same... script passing the example...

2023-12-01 08:41 UTC, elguardian commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/README.md
> +```
Observations (no need fix)
1) does not work with podman
2) host-gateway not recognized in some version (company rhel distro)
3) keycloack realm is not being loaded (does not bind file system)


during execution got this error. Probably podamn problem


`[kogito-example-service] | 2023-12-01 08:16:17,837 ERROR [org.kie.kog.job.man.qua.VertxJobsService] (vert.x-eventloop-thread-1) Scheduling of job Job{id='94c105b2-489d-44b7-ab62-f1d8d7ec870f', correlationId='94c105b2-489d-44b7-ab62-f1d8d7ec870f', state=null, schedule=TimerSchedule{startTime='2023-12-01T08:18:17.476Z', repeatCount=0, delay=null, delayUnit='MILLIS'}, retry=null, recipient=HttpRecipient{url='http://172.17.0.1:8080/management/jobs/hiring/instances/40d71796-27f2-423a-a095-aadb12ccf078/timers/1', method='POST', headers={processInstanceId=40d71796-27f2-423a-a095-aadb12ccf078, nodeInstanceId=5e57cb85-feb4-45ba-82ac-4bd8cf0c5f07, processId=hiring, rootProcessId=null, rootProcessInstanceId=null, Content-Type=application/json}, queryParams={}, payload=org.kie.kogito.jobs.service.api.recipient.http.HttpRecipientJsonPayloadData@ed2358d0} org.kie.kogito.jobs.service.api.recipient.http.HttpRecipient@346e4a23, executionTimeout=null, executionTimeoutUnit=null} failed with response code 0: io.netty.channel.ConnectTimeoutException: connection timed out: /172.17.0.1:8580
`

2023-12-01 08:41 UTC, elguardian commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/README.md
> +mvn clean package quarkus:dev -Pdevelopment
it seems there is a problem.

`2023-12-01 09:31:02,337 li-1a3d434c-313e-11b2-a85c-bf221e769faa ERROR [org.kie.kogito.quarkus.workflow.devservices.DataIndexEventPublisher:71] (vert.x-eventloop-thread-1) Failed to send message to Data Index: io.vertx.core.impl.NoStackTraceThrowable: Response status code 404 is not equal to 202`

2023-12-01 08:41 UTC, elguardian commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/README.md
> +mvn clean package quarkus:dev -Pdevelopment
`2023-12-01 09:40:10,663 li-1a3d434c-313e-11b2-a85c-bf221e769faa INFO  [org.kie.kogito.quarkus.workflow.deployment.devservices.DataIndexInMemoryContainer:68] (docker-java-stream-1699578725) STDOUT: 2023-12-01 08:40:10,614 ERROR [io.sma.rea.mes.provider] (executor-thread-0) SRMSG00200: The method org.kie.kogito.index.service.messaging.BlockingMessagingEventConsumer#onProcessInstanceEvent has thrown an exception: java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.NullNode cannot be cast to class com.fasterxml.jackson.databind.node.ObjectNode (com.fasterxml.jackson.databind.node.NullNode and com.fasterxml.jackson.databind.node.ObjectNode are in unnamed module of loader io.quarkus.bootstrap.runner.RunnerClassLoader @6f75e721)
`

I guess this is related to the start date in a node.

2023-12-14 14:50 UTC, pefernan commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/README.md
> +```
Apparently that's a missing feature on `podman` prior `4.7`. I'll add a note warning about this.

2024-01-17 17:52 UTC, kmacedovarela commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/README.md
> +    <img width=75%  src="docs/images/MC_details_1.png">
broken image, probably cuz of the capital letters on the filename.

2024-01-17 17:52 UTC, kmacedovarela commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/README.md
> +    <img width=75%  src="docs/images/MC_details_2_IT_executed_job.png">
broken image, probably cuz of the capital letters on the filename.

2024-01-25 11:13 UTC, pefernan commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/README.md
> +    <img width=75%  src="docs/images/MC_details_2_IT_executed_job.png">
@kmacedovarela thank you for your review, I haven't finished with the readme yet.

2024-01-26 22:09 UTC, martinweiler commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/README.md
> +This example also demonstrates how to configure the whole *Kogito* environment using the new *Simplified Architecture* that
Is "Simplified Architecture" the term we want to use? I know we have used it internally and it makes sense if you are aware of initial architecture design, but new users might get a wrong idea of what "simplified" means. WDYT @porcelli @kmacedovarela ?

2024-01-26 22:29 UTC, martinweiler commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/README.md
> +- Kafka: 9092
remove kafka

2024-01-29 07:57 UTC, elguardian commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/docker-compose/docker-compose.yml
> +      - ./persistence:/home/kogito/data/protobufs/
do we need protobuf for postgresql indexing ¿?

2024-01-29 07:58 UTC, elguardian commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/docker-compose/docker-compose.yml
> +      KOGITO_QUARKUS_JVM_PROPS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Dquarkus.datasource.reactive.url=postgresql://postgres:5432/kogito
probably not needed.

2024-01-29 07:59 UTC, elguardian commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/src/main/resources/application.properties
> +%container.quarkus.jib.base-jvm-image=quay.io/kiegroup/kogito-runtime-jvm-nightly:latest
we should open a jira bout this.

2024-01-29 08:01 UTC, elguardian commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/docker-compose/README.md
> +- Keycloak
data audit ¿?

2024-01-29 08:02 UTC, elguardian commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/README.md
> +This example also demonstrates how to configure the whole *Kogito* environment using the new *Simplified Architecture* that
I guess who is our target as user. If we are focusing engineers probably classic or monolith could be ok.

2024-01-29 08:04 UTC, elguardian requested changes
data audit IMO should not be  out of this.

2024-01-29 09:17 UTC, pefernan commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/docker-compose/docker-compose.yml
> +      KOGITO_QUARKUS_JVM_PROPS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Dquarkus.datasource.reactive.url=postgresql://postgres:5432/kogito
gosh, a leftover

2024-01-29 21:13 UTC, martinweiler commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/README.md
> +This example also demonstrates how to configure the whole *Kogito* environment using the new *Simplified Architecture* that
We agreed to use **Compact** Architecture now

2024-01-29 21:16 UTC, martinweiler commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/README.md
> +This will build the example quarkus application and create a Docker image that will be started in the
in the ...(?)

2024-01-29 21:59 UTC, martinweiler commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/docker-compose/docker-compose.yml
> +    image: postgres:13.4-alpine3.14
why are we using such an old version here? wouldn't it make sense to have something more recent out-of-the-box, eg. postgres:16.1-alpine3.19

2024-01-29 22:00 UTC, martinweiler commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/docker-compose/docker-compose.yml
> +    image: dpage/pgadmin4:7.8
same as with postgres, we might want to use a more recent version (eg. dpage/pgadmin4:8.2)?

2024-01-29 22:06 UTC, porcelli commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/docker-compose/docker-compose.yml
> +    image: postgres:13.4-alpine3.14
@martinweiler my guess is because we have already defined the postgres dependency somewhere else and this is just aligned.

2024-01-30 10:08 UTC, pefernan commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/docker-compose/docker-compose.yml
> +      - ./persistence:/home/kogito/data/protobufs/
Well, that's to enable data-index index the domain models, that's not necessarily needed.

2024-01-30 10:10 UTC, pefernan commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/src/main/resources/application.properties
> +%container.quarkus.jib.base-jvm-image=quay.io/kiegroup/kogito-runtime-jvm-nightly:latest
yea, we still don't have the `quay.io/kiegroup/kogito-runtime-jvm` image updated with the latest chnages, I'd keep this like this and do the upgrade after we have the image publisehd.

2024-01-30 11:22 UTC, pefernan commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/docker-compose/README.md
> +- Keycloak
+1 Will add `data-audit` as colocated service, so I'll mention it in the main `README.md`

2024-01-30 17:07 UTC, pefernan commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/docker-compose/docker-compose.yml
> +    image: postgres:13.4-alpine3.14
Upgraded to `postgres:16.1-alpine3.19`

2024-01-30 17:08 UTC, pefernan commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/docker-compose/docker-compose.yml
> +    image: dpage/pgadmin4:7.8
Upgraded to `dpage/pgadmin4:8.2` (and also adding default configuration)

2024-01-30 19:33 UTC, martinweiler approved these changes
Great work @pefernan

2024-01-31 09:05 UTC, elguardian commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/src/main/resources/application.properties
> +quarkus.flyway.locations=classpath:/db/migration,classpath:/db/jobs-service
I don't see the classpath for data index pgsql here.

2024-01-31 09:05 UTC, elguardian commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/src/main/resources/application.properties
> +quarkus.hibernate-orm.database.generation=update
this needs to be removed

2024-01-31 09:05 UTC, elguardian requested changes
needs some changes in the conf

2024-01-31 11:16 UTC, pefernan commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/src/main/resources/application.properties
> +quarkus.hibernate-orm.database.generation=update
done

2024-01-31 11:16 UTC, pefernan commented on kogito-quarkus-examples/process-usertasks-timer-data-index-persistence-addon-quarkus/src/main/resources/application.properties
> +quarkus.flyway.locations=classpath:/db/migration,classpath:/db/jobs-service
done

2024-02-01 10:09 UTC, elguardian approved these changes
LGTM

2024-02-01 16:37 UTC, merged