[incubator-kie-issues#1596] Adding Business Calendar Example
apache/incubator-kie-examples pull request #2036
Opened 2024-11-05 16:31 UTC by Abhitocode

Closes: https://github.com/apache/incubator-kie-issues/issues/1596

Add an example ensuring business calendar functionality to kogito-quarkus-examples.
The example should include a simple process that uses a business calendar. The example should contain a good README with clear step by step instructions, and has to incorporate all supporting resources required. The priority would be having this example for Quarkus.

Note: PR still in progress, files needs to be updated.

2024-11-05 16:31 UTC, gitgabrio commented
Reopened from https://github.com/apache/incubator-kie-kogito-examples/pull/2031

2024-11-06 17:12 UTC, kie-ci3 commented
**PR job** `#2` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/2036 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2036/2/display/redirect

**Test results:**
- PASSED: 123
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2036/2/testReport/org.kie.kogito.calendar/CreditCardProcessIT/testCardPaymentInWorkingDay/">org.kie.kogito.calendar.CreditCardProcessIT.testCardPaymentInWorkingDay</a></summary>
1 expectation failed.<br/>Response body doesn't match expectation.<br/>Expected: "[]"<br/>  Actual: [{"id":"34985152-e934-422d-befe-0f6ab4333bfd","creditCardNumber":null,"creditCardDetails":{"cardNumber":"434354343","status":"Bill Due"}}]<br/>
</details>

2024-11-06 18:46 UTC, kie-ci3 commented
**PR job** `#3` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/2036 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2036/3/display/redirect

**Test results:**
- PASSED: 170
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2036/3/testReport/org.kie.kogito.calendar/CreditCardProcessIT/testCardPaymentInWorkingDay/">org.kie.kogito.calendar.CreditCardProcessIT.testCardPaymentInWorkingDay</a></summary>
1 expectation failed.<br/>Response body doesn't match expectation.<br/>Expected: "[]"<br/>  Actual: [{"id":"4267f444-8674-4514-9f79-186ed782bc0f","creditCardNumber":null,"creditCardDetails":{"cardNumber":"434354343","status":"Bill Due"}}]<br/>
</details>

2024-11-06 21:33 UTC, kie-ci3 commented
**PR job** `#4` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/2036 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2036/4/display/redirect

**Test results:**
- PASSED: 394
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2036/4/testReport/org.kie.kogito.examples.quarkus/GrafanaDockerComposeIT/testGrafanaDashboards/">org.kie.kogito.examples.quarkus.GrafanaDockerComposeIT.testGrafanaDashboards</a></summary>
1 expectation failed.<br/>JSON path title doesn't match.<br/>Expected: a collection containing "dmn-drools-quarkus-metrics_999-SNAPSHOT - hello - Operational Dashboard"<br/>  Actual: <[dmn-drools-quarkus-metrics_999-SNAPSHOT - Custom - Domain Dashboard, dmn-drools-quarkus-metrics_999-SNAPSHOT - Custom - Operational Dashboard, dmn-drools-quarkus-metrics_999-SNAPSHOT - Hello - Domain Dashboard, dmn-drools-quarkus-metrics_999-SNAPSHOT - LoanEligibility - Domain Dashboard, dmn-drools-quarkus-metrics_999-SNAPSHOT - LoanEligibility - Operational Dashboard]><br/>
</details>

2024-11-11 11:12 UTC, gitgabrio requested changes

2024-11-11 11:12 UTC, gitgabrio commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +This project is an illustrative example demonstrating the impact of a business calendar on process execution within a Quarkus application . It showcases a business process involving credit card bill
HI @Abhitocode 
typo at `Quarkus application . It showcases` - pls remove space before the dot

2024-11-11 11:12 UTC, gitgabrio commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +When running in either Quarkus Development or Native mode, we also leverage the [Quarkus OpenAPI extension](https://quarkus.io/guides/openapi-swaggerui#use-swagger-ui-for-development) that exposes [S
HI @Abhitocode 
please double check http://localhost:8080/swagger-ui/ it is the actual URL inside quarkus

2024-11-11 11:12 UTC, gitgabrio commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +## Comparision of timer with and without calendar.properties
Typo `Comparision`

2024-11-11 11:12 UTC, gitgabrio commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +The timer for the Verify Payment task will follow a straightforward countdown based on real time. If the specified time elapses i.e., 1 second, it immediately moves to cancel payment task, regardless
IINW, without calendar.properties, the behavior is strongly related to the current time on the machine that execute it. Please specify/clarify that

2024-11-11 11:12 UTC, gitgabrio commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +#define today's date as holiday for testing purposes
Please remove the commented lines in the example: there is no need to specify them

2024-11-11 11:12 UTC, gitgabrio commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +* For repeated holidays in a year
Please provide a quick but clear explanation of overall calendar.properties format, not only examples

2024-11-11 11:12 UTC, gitgabrio commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +* The node 'Start' for the process 'BusinessCalendarCreditBill', identified by 08ea5258-9d91-4f05-a8d8-184107c042ed, was triggered at 08:54:28,621.
As mentioned before, IINW the behaviour is strongly dependant on the curennt time on executing machine: please xplain that, or correct me if I'm wrong

2024-11-11 11:12 UTC, gitgabrio commented on kogito-quarkus-examples/pom.xml
> +        <module>process-business-calendar-example</module>
Please follow the order as all the other modules: move that declaration below

2024-11-12 08:11 UTC, yesamer commented
Hi @Abhitocode, if this is Ready for review, please move its status from Draft to "Ready for review". Thanks

2024-11-12 08:48 UTC, kie-ci3 commented
**PR job** `#11` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>



build-chain build full_downstream  -f 'https://raw.githubusercontent.com/${AUTHOR:apache}/incubator-kie-kogito-pipelines/${BRANCH:main}/.ci/buildchain-config-pr-cdb.yaml' -o 'bc' -p apache/incubator-kie-kogito-examples -u https://github.com/apache/incubator-kie-kogito-examples/pull/2036 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2036/11/display/redirect

**Test results:**
- PASSED: 400
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/pullrequest_jobs/job/kogito-examples-pr/job/PR-2036/11/testReport/org.kie.kogito.examples.quarkus/GrafanaDockerComposeIT/testGrafanaDashboards/">org.kie.kogito.examples.quarkus.GrafanaDockerComposeIT.testGrafanaDashboards</a></summary>
1 expectation failed.<br/>JSON path title doesn't match.<br/>Expected: a collection containing "dmn-drools-quarkus-metrics_999-SNAPSHOT - Custom - Operational Dashboard"<br/>  Actual: <[dmn-drools-quarkus-metrics_999-SNAPSHOT - Custom - Domain Dashboard, dmn-drools-quarkus-metrics_999-SNAPSHOT - Hello - Domain Dashboard, dmn-drools-quarkus-metrics_999-SNAPSHOT - hello - Operational Dashboard, dmn-drools-quarkus-metrics_999-SNAPSHOT - LoanEligibility - Domain Dashboard, dmn-drools-quarkus-metrics_999-SNAPSHOT - LoanEligibility - Operational Dashboard]><br/>
</details>

2024-11-12 19:55 UTC, martinweiler commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +## Understanding timer behaviour with respect to working and non-working days without calendar.properties
@Abhitocode as discussed, this whole section (until line 249) needs to be updated. If there is no calendar.properties file in the application, then no BusinessCalendarImpl instance will be created. All due date calculations are then based on time only.

2024-11-12 19:56 UTC, martinweiler requested changes
The section on running without calendar.properties file needs to be updated.

2024-11-13 08:33 UTC, yesamer reviewed
Reporting a couple of minor points

2024-11-13 08:33 UTC, yesamer commented on kogito-quarkus-examples/process-business-calendar-example/src/main/resources/calendar.properties
> +business.weekend.days = 8
@Abhitocode Please remove unnecessary whitespaces

2024-11-13 08:33 UTC, yesamer commented on kogito-quarkus-examples/process-business-calendar-example/src/main/resources/calendar.properties
> +business.end.hour=24
@Abhitocode Please add the License header as you did in `application.properties`

2024-11-13 10:36 UTC, jomarko reviewed
Thank you for this PR. It seems very good feature. I have done some tests locally. I agree with others that maybe we could enhance the documentation a little bit.

2024-11-13 10:36 UTC, jomarko commented on kogito-quarkus-examples/process-business-calendar-example/src/main/java/org/kie/kogito/calendar/bill/CreditCardService.java
> +        creditCardDetails.setStatus("Payment cancelled, money will be refunded if it it is debited");
We have a typo here.

2024-11-13 10:36 UTC, jomarko commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +A service task where the credit card details are validated, ensuring the payment is processed under valid terms.
Looking on the properties of the 'Verify Payment node', I see it is completely empty. It is not assigned to any user, any group. So wanted to ask, is that intentional to demonstrate the timer behavior?

2024-11-13 10:36 UTC, jomarko commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +java -jar target/quarkus-app/quarkus-run.jar
this somehow does not work on my machine:
![Screenshot 2024-11-13 110210](https://github.com/user-attachments/assets/0f8696f0-3821-4691-916a-e592a2e8a768)
![Screenshot 2024-11-13 110330](https://github.com/user-attachments/assets/8d29ac95-10c5-422a-bf7e-11f5d265a088)

2024-11-13 10:36 UTC, jomarko commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +mvn clean package -Pnative
I was not able to finish this build:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:16 min
[INFO] Finished at: 2024-11-13T11:09:29+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.8.6:build (default) on project process-business-calendar-example: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 1
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:468)
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:258)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:840)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

2024-11-13 10:36 UTC, jomarko commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +business.holidays=2024-11-07             # Add custom holidays that are non-working days, specified in the format defined by business.holiday.date.format
how to define multiple days or periods, is that possible? asking because there are usually more holidays during the year

2024-11-13 10:36 UTC, jomarko commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +business.weekend.days = 8                # Define specific days as weekends (e.g., setting business.weekend.days=1,2 for Sunday and Monday, if weekend has to considered as working days, consider a va
I am not sure, is the Sunday 1, or the Monday is 1? I would expect Monday is 1.Maybe we could be more explicit about this? What do you think?

2024-11-13 10:36 UTC, jomarko commented on kogito-quarkus-examples/process-business-calendar-example/src/main/resources/org/kie/calendar/bill/BPMN2-BusinessCalendarBankTransaction.bpmn2
> +  <bpmn2:process id="BusinessCalendarCreditBill" drools:packageName="org.kie.calendar.bill" drools:version="1.0" drools:adHoc="false" name="BusinessCalendar-CreditBill" isExecutable="true" processTyp
maybe we could unify the packages, in src/main/java we have `org.kie.kogito.calendar.bill` while in src/main/resources we have `org.kie.calendar.bill`

2024-11-13 16:57 UTC, Abhitocode commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +business.weekend.days = 8                # Define specific days as weekends (e.g., setting business.weekend.days=1,2 for Sunday and Monday, if weekend has to considered as working days, consider a va
Sunday is 7, Il make sure to include the info in the readme

2024-11-13 16:57 UTC, Abhitocode commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +A service task where the credit card details are validated, ensuring the payment is processed under valid terms.
That is not intentional, as it is not assigned , it can be completed by any user just in the example perspective.

2024-11-14 05:48 UTC, Abhitocode commented on kogito-quarkus-examples/process-business-calendar-example/src/main/resources/calendar.properties
> +business.end.hour=24
okay

2024-11-14 05:52 UTC, Abhitocode commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +java -jar target/quarkus-app/quarkus-run.jar
I tried again, works for, not sure exactly what might be causing the issue in your case
![image](https://github.com/user-attachments/assets/96cea3ea-dffd-423c-abf0-85df54b89a3b)

2024-11-14 05:55 UTC, Abhitocode commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +business.holidays=2024-11-07             # Add custom holidays that are non-working days, specified in the format defined by business.holiday.date.format
multiple holidays: 2024-11-13, 2024-11-14
In a range 2024-11-14:2024-11-14

Thank you for the pointing it, just remebered to add the same in the readme too.

2024-11-14 07:33 UTC, yesamer commented on kogito-quarkus-examples/process-business-calendar-example/src/main/resources/calendar.properties
> +business.weekend.days =1
```suggestion
business.weekend.days=1
```

2024-11-14 07:34 UTC, yesamer commented on kogito-quarkus-examples/process-business-calendar-example/src/main/resources/calendar.properties
> +business.days.per.week =6
```suggestion
business.days.per.week=6
```

2024-11-14 10:52 UTC, yesamer commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +A service task where the credit card details are validated, ensuring the payment is processed under valid terms.
@Abhitocode `Verify Payment` is a User Task
```suggestion
A user task where the credit card details are validated, ensuring the payment is processed under valid terms.
```

2024-11-14 10:54 UTC, yesamer commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +Attached to a human task to simulate waiting for manual confirmation or user action. This timer can be configured to react differently based on the presence of the business calendar.
@Abhitocode Please use the official name based on bpmn standard: User Task instead of Human Task.
```suggestion
Attached to a user task to simulate waiting for manual confirmation or user action. This timer can be configured to react differently based on the presence of the business calendar.
```

2024-11-14 11:05 UTC, yesamer commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +business.timezone=America/Toronto        # Optionally specify the timezone for your business hours, if not configured, it corresponds to systems time/day.
Wrong property name
```suggestion
business.cal.timezone=America/Toronto        # Optionally specify the timezone for your business hours, if not configured, it corresponds to systems time/day.
```

2024-11-14 14:31 UTC, Abhitocode commented on kogito-quarkus-examples/process-business-calendar-example/README.md
> +java -jar target/quarkus-app/quarkus-run.jar
enabled it in the application.properties, should work now.

2024-11-14 14:33 UTC, gitgabrio approved these changes
Hi @Abhitocode 
Many thanks for the example. And, mostly, for the documentation ❤️ 
LGTM

2024-11-14 14:36 UTC, yesamer approved these changes
@Abhitocode Thank you, well done!

2024-11-14 16:34 UTC, martinweiler approved these changes
Great work @Abhitocode 
Thanks for your diligence incorporating all the feedback!

2024-11-14 18:31 UTC, jomarko approved these changes
Thank you for updates @Abhitocode

2024-11-14 18:34 UTC, merged