KOGITO-1121 - Create advanced example for kogito + serverless workflo…
apache/incubator-kie-examples pull request #213
Opened 2020-04-11 16:04 UTC by tsurdilo

…w - quarkus

2020-04-11 16:06 UTC, tsurdilo commented
if possible please merge https://github.com/kiegroup/kogito-runtimes/pull/436 first

2020-04-13 14:19 UTC, ricardozanini requested changes
One small thing, same for Springboot.

2020-04-13 14:19 UTC, ricardozanini commented on serverless-workflow-service-calls-quarkus/README.md
> +java -jar target/serverless-workflow-service-calls-quarkus-{version}-runner.jar
Same thing here regarding the jar final name

2020-04-13 16:36 UTC, tsurdilo commented on serverless-workflow-service-calls-quarkus/README.md
> +java -jar target/serverless-workflow-service-calls-quarkus-{version}-runner.jar
fixed. Thanks!

2020-04-13 22:59 UTC, ricardozanini approved these changes
Tested OK

2020-04-14 01:18 UTC, cristianonicolai approved these changes

2020-04-14 05:57 UTC, jstastny-cz requested changes

2020-04-14 05:57 UTC, jstastny-cz commented on serverless-workflow-service-calls-quarkus/README.md
> +mvn clean package quarkus:dev
Here we need really just the 'compile', please change so that all examples are in sync.

2020-04-14 05:57 UTC, jstastny-cz commented on serverless-workflow-service-calls-quarkus/README.md
> +### Compile and Run in JVM mode
Compile -> Package

2020-04-14 05:57 UTC, jstastny-cz commented on serverless-workflow-service-calls-quarkus/README.md
> +### Compile and Run using Local Native Image
Compile -> Package

2020-04-14 05:57 UTC, jstastny-cz commented on serverless-workflow-service-calls-quarkus/pom.xml
> +            <artifactId>maven-failsafe-plugin</artifactId>
currently there are not native integration tests for quarkus, either add those or we can remove the failsafe configuration (as long as there are not any we'd like to exclude then)

2020-04-14 05:57 UTC, jstastny-cz commented on serverless-workflow-service-calls-quarkus/src/test/java/org/kogito/serverless/examples/CountriesResourceTest.java
> +public class CountriesResourceTest {
I think we should move the tests to integration-test phase, they rely on an external service.

2020-04-14 05:57 UTC, jstastny-cz commented on serverless-workflow-service-calls-quarkus/src/test/java/org/kogito/serverless/examples/CountryServiceWorkflowTest.java
> +public class CountryServiceWorkflowTest {
I think we should move the tests to integration-test phase, they rely on an external service.

2020-04-14 12:16 UTC, tsurdilo commented on serverless-workflow-service-calls-quarkus/pom.xml
> +            <artifactId>maven-failsafe-plugin</artifactId>
This is present in almost all examples. Should we not create a Jira to remove it from all examples not just 1?

2020-04-14 12:18 UTC, tsurdilo commented on serverless-workflow-service-calls-quarkus/src/test/java/org/kogito/serverless/examples/CountriesResourceTest.java
> +public class CountriesResourceTest {
this service is present during any of the test phases so not sure i'd agree. Same is done in other examples as well, for example: https://github.com/kiegroup/kogito-examples/tree/stable/kogito-service-rest-call-quarkus/src/test/java/org/acme/travels
so if we do this lets do it across the board imo?

2020-04-14 12:18 UTC, tsurdilo commented on serverless-workflow-service-calls-quarkus/src/test/java/org/kogito/serverless/examples/CountryServiceWorkflowTest.java
> +public class CountryServiceWorkflowTest {
same reply as above. let's fix this across all examples imo

2020-04-14 12:19 UTC, tsurdilo commented on serverless-workflow-service-calls-quarkus/README.md
> +mvn clean package quarkus:dev
fixed thanks.

2020-04-14 12:19 UTC, tsurdilo commented on serverless-workflow-service-calls-quarkus/README.md
> +### Compile and Run in JVM mode
fixed - thanks!

2020-04-14 12:19 UTC, tsurdilo commented on serverless-workflow-service-calls-quarkus/README.md
> +### Compile and Run using Local Native Image
fixed - thanks!

2020-04-15 08:00 UTC, jstastny-cz commented on serverless-workflow-service-calls-quarkus/pom.xml
> +            <artifactId>maven-failsafe-plugin</artifactId>
Ah, alright. It's not harmful to keep, just not used.

2020-04-15 08:04 UTC, jstastny-cz commented on serverless-workflow-service-calls-quarkus/src/test/java/org/kogito/serverless/examples/CountriesResourceTest.java
> +public class CountriesResourceTest {
See your example: 
```
@Disabled("depends on https://petstore.swagger.io existing users")
```
that's exactly the reason, such external dependency might break the build (especially troubling in CI). Solution would be just to rename the test class file Test-> IT .... failsafe configuration is in place.

2020-04-15 08:04 UTC, jstastny-cz commented on serverless-workflow-service-calls-quarkus/src/test/java/org/kogito/serverless/examples/CountryServiceWorkflowTest.java
> +public class CountryServiceWorkflowTest {
Same reply as above ;-)

2020-04-15 12:21 UTC, tsurdilo commented
Could someone please kick the build for this pr again? Thanks!

2020-04-15 12:42 UTC, tsurdilo commented
@jstastny-cz updated tests to be ran in integration phase, I did use however @Tag("integration")
as described in the quarkus guides - https://quarkus.io/guides/tests-with-coverage#separating-executions-of-unit-tests-and-integration-tests

2020-04-15 17:00 UTC, jstastny-cz approved these changes

2020-04-16 13:57 UTC, tsurdilo commented
rebased

2020-04-16 15:52 UTC, cristianonicolai commented
@evacchi good to merge?

2020-04-16 16:30 UTC, merged