[KOGITO-1920] - Example for persistence in Mongo DB with Quarkas
apache/incubator-kie-examples pull request #242
Opened 2020-04-21 15:14 UTC by swati-kale

Signed-off-by: Swati Kale <swkale@redhat.com>

2020-04-22 13:50 UTC, ricardozanini requested changes
Hi Swati! Many thanks for this example. Could you please add the following:
1. Rename the example to `process-mongodb-persistence-quarkus`
2. Give an operator example. Every example in this repo has an `operator` directory with an example, you could take one from there. I understand that you also need to deploy mongodb via template files/other operator. Could you please add those as well?

Many thanks!

2020-04-22 15:04 UTC, mswiderski commented on kogito-mongodb-persistence-quarkus/pom.xml
> +      <artifactId>mongodb-persistence-addon</artifactId>
where is this implementation of the persistence add-on?

2020-04-22 16:42 UTC, swati-kale commented on kogito-mongodb-persistence-quarkus/pom.xml
> +      <artifactId>mongodb-persistence-addon</artifactId>
I am working on it as I have to do some code changes based on recent changes in PersistenceGenerator in codegen and other modules.I will create a PR soon.

2020-04-22 20:08 UTC, ricardozanini commented on kogito-mongodb-persistence-quarkus/pom.xml
> +      <artifactId>mongodb-persistence-addon</artifactId>
Without this artifact we can't test your example

2020-04-23 05:56 UTC, cristianonicolai reviewed
@swati-kale please also provide integration tests for this example.

2020-04-23 05:56 UTC, cristianonicolai commented on kogito-mongodb-persistence-quarkus/.gitignore
> +bin/
no need to add, as it should be handled by root `.gitignore`

2020-04-23 05:56 UTC, cristianonicolai commented on kogito-mongodb-persistence-quarkus/README.md
> +  - Java 1.8.0+ installed
Base Java is 11 now

2020-04-23 05:56 UTC, cristianonicolai commented on kogito-mongodb-persistence-quarkus/README.md
> +  - Maven 3.5.4+ installed
```suggestion
  - Maven 3.6.2+ installed
```

2020-04-23 05:56 UTC, cristianonicolai commented on kogito-mongodb-persistence-quarkus/pom.xml
> +
could you please remove these empty lines

2020-04-23 05:56 UTC, cristianonicolai commented on kogito-mongodb-persistence-quarkus/pom.xml
> +      <artifactId>mongodb-persistence-addon</artifactId>
@swati-kale, in that case, could you mark this PR as Draft until you have all the available bits ready to be tested?

2020-04-23 05:56 UTC, cristianonicolai commented on kogito-mongodb-persistence-quarkus/pom.xml
> +      <version>${kogito.version}</version>
version should be managemend via bom already. please remove.

2020-04-23 05:56 UTC, cristianonicolai commented on kogito-mongodb-persistence-quarkus/src/main/java/org/acme/travels/Address.java
> +package org.acme.travels;
missing copywrite to Java classes

2020-04-23 05:59 UTC, cristianonicolai commented
@swati-kale @ricardozanini @evacchi I'm not sure we need a new example or simply consolidate all persistence related examples on a `kogito-persistence-example` that has different profiles.

2020-04-23 08:32 UTC, evacchi commented
@cristianonicolai I like that idea, that would strengthen the idea that backends are pluggable

2020-04-23 13:46 UTC, swati-kale commented
Thanks, I will take care of all the above change requests.

2020-04-23 19:27 UTC, ricardozanini commented
> @swati-kale @ricardozanini @evacchi I'm not sure we need a new example or simply consolidate all persistence related examples on a `kogito-persistence-example` that has different profiles.

I'd rather having this example since users willing to use MongoDB could find this easily (also SEO). I mean, is more user friendly IMO. But I'm ok by moving this to the `persistence` example instead.

2020-04-24 05:27 UTC, cristianonicolai commented
> > @swati-kale @ricardozanini @evacchi I'm not sure we need a new example or simply consolidate all persistence related examples on a `kogito-persistence-example` that has different profiles.
> 
> I'd rather having this example since users willing to use MongoDB could find this easily (also SEO). I mean, is more user friendly IMO. But I'm ok by moving this to the `persistence` example instead.

Updating the text in the main readme here https://github.com/kiegroup/kogito-examples#process-with-infinispan-persistence adding Mongo can help with that.

2020-04-24 14:27 UTC, ricardozanini commented
@cristianonicolai so we move this example to https://github.com/kiegroup/kogito-examples#process-with-infinispan-persistence and add a `mongodb` profile there, also adding a section mentioning how to set this up. Is that ok?

2020-04-24 14:33 UTC, mswiderski commented
> so we move this example to https://github.com/kiegroup/kogito-examples#process-with-infinispan-persistence and add a mongodb profile there, also adding a section mentioning how to set this up. Is that ok?

-1 on having single project with all types of persistence types, this just makes it very confusing for users. If you would like to test single project with different profiles to validate it works this might make some sense but from example/quickstart point of view it makes it easy harder to get it. Plus you could use certain persistence add-on to show why it is better (in what cases) then the others. Just my 2c....

2020-04-24 14:37 UTC, swati-kale commented
> > so we move this example to https://github.com/kiegroup/kogito-examples#process-with-infinispan-persistence and add a mongodb profile there, also adding a section mentioning how to set this up. Is that ok?
> 
> -1 on having single project with all types of persistence types, this just makes it very confusing for users. If you would like to test single project with different profiles to validate it works this might make some sense but from example/quickstart point of view it makes it easy harder to get it. Plus you could use certain persistence add-on to show why it is better (in what cases) then the others. Just my 2c....
So shall I keep it seperate (same as now) and add a section on main readme?

2020-04-24 15:43 UTC, ricardozanini commented
> > so we move this example to https://github.com/kiegroup/kogito-examples#process-with-infinispan-persistence and add a mongodb profile there, also adding a section mentioning how to set this up. Is that ok?
> 
> -1 on having single project with all types of persistence types, this just makes it very confusing for users. If you would like to test single project with different profiles to validate it works this might make some sense but from example/quickstart point of view it makes it easy harder to get it. Plus you could use certain persistence add-on to show why it is better (in what cases) then the others. Just my 2c....

@cristianonicolai that's makes two against one. You lose. :laughing: 

> So shall I keep it seperate (same as now) and add a section on main readme?

Keep it separated for now, make sure that it works with the new add-on and on Monday we can discuss with @cristianonicolai

2020-04-25 06:15 UTC, cristianonicolai commented
I think my concern is more around maintaining all of these examples, and if we add a new project for every single tech that we support, think different message brokers etc. Then it could have so many examples that is hard to maintain but even confusing to users? In theory if we are simply showing that it can work, not a different use case, I think a separated profile would be enough.
@ricardozanini technically a draw as @evacchi was supporting it as well hehehe but I'm not against the idea, I see your and @mswiderski point.

2020-04-25 09:02 UTC, mswiderski commented
@cristianonicolai the point is that persistence is important and chosing one over the other should be clearly understood. So in my opinion hiding all in one example will not help. Plus different persistence mechanisms will have different needs when it comes to data for instance or how it actually marshals/unmarshals variables.

2020-06-10 14:11 UTC, swati-kale commented on kogito-mongodb-persistence-quarkus/pom.xml
> +      <artifactId>mongodb-persistence-addon</artifactId>
I have added the addon here, https://github.com/kiegroup/kogito-runtimes/pull/477

2020-06-23 13:59 UTC, Sgitario requested changes

2020-06-23 13:59 UTC, Sgitario commented on pom.xml
> +    <module>process-mongodb-persistence-quarkus</module>
What about having a single process-persistence-quarkus example with multiple maven profiles: one for Infinispan and another for Mongodb?
This way we can save up lot of duplicate code. What do you think? @ricardozanini @cristianonicolai

2020-06-23 13:59 UTC, Sgitario commented on process-mongodb-persistence-quarkus/README.md
> +This quickstart requires an MongDB server to be available and by default expects it to be on default port(27017) and localhost.
Typo here: MongDB

2020-06-23 13:59 UTC, Sgitario commented on process-mongodb-persistence-quarkus/README.md
> +In the [`operator`](operator) directory you'll find the custom resources needed to deploy this example on OpenShift with the [Kogito Operator](https://docs.jboss.org/kogito/release/latest/html_single
I think the operator will deploy Infinispan by default, so maybe we need to add more details about how to install MongoDB in Openshift and configure the operator accordingly?

2020-06-23 13:59 UTC, Sgitario commented on process-mongodb-persistence-quarkus/operator/process-mongodb-persistence-quarkus.yaml
> +  enablePersistence: true
This will configure the KogitoApp using an Infinispan instance, right?

2020-06-23 13:59 UTC, Sgitario commented on process-mongodb-persistence-quarkus/pom.xml
> +<?xml version="1.0"?>
The format is wrong here: It should use 2 spaces instead of tabs for indendation.

2020-06-23 13:59 UTC, Sgitario commented on process-mongodb-persistence-quarkus/src/test/java/org/acme/deals/DealsRestIT.java
> +                                                                                                .waitingFor(Wait.forLogMessage(".*build index done.*", 1));
This has changed in the master branch, update and follow the same approach as done for Infinispan.

2020-06-29 19:44 UTC, swati-kale commented on process-mongodb-persistence-quarkus/src/test/java/org/acme/deals/DealsRestIT.java
> +                                                                                                .waitingFor(Wait.forLogMessage(".*build index done.*", 1));
I will check infinispan implementation. Thanks>

2020-07-29 14:27 UTC, swati-kale commented on process-mongodb-persistence-quarkus/README.md
> +In the [`operator`](operator) directory you'll find the custom resources needed to deploy this example on OpenShift with the [Kogito Operator](https://docs.jboss.org/kogito/release/latest/html_single
removed the operator folder as it will be taken care in other Jira.

2020-07-29 14:28 UTC, swati-kale commented on process-mongodb-persistence-quarkus/operator/process-mongodb-persistence-quarkus.yaml
> +  enablePersistence: true
same as above

2020-07-29 14:29 UTC, swati-kale commented on process-mongodb-persistence-quarkus/src/test/java/org/acme/deals/DealsRestIT.java
> +                                                                                                .waitingFor(Wait.forLogMessage(".*build index done.*", 1));
Added integration test following infinispan.

2020-07-31 09:30 UTC, cristianonicolai commented
@swati-kale, please wait for kiegroup/kogito-runtimes#625 to get merged then you can centralize the MongoDB common test part in there.

2020-07-31 09:30 UTC, cristianonicolai reviewed
@swati-kale, please wait for kiegroup/kogito-runtimes#625 to get merged then you can centralize the MongoDB common test part in there.

2020-07-31 09:30 UTC, cristianonicolai commented on process-mongodb-persistence-quarkus/src/main/resources/application.properties
> +quarkus.log.category."io.quarkus.arc.processor".level=DEBUG
please remove this log setting as it might be too verbose for most people and CI logs.

2020-07-31 09:30 UTC, cristianonicolai commented on process-mongodb-persistence-quarkus/src/main/resources/application.properties
> +quarkus.native.additional-build-args =-H:ReflectionConfigurationFiles=reflection-config.json,\
is this really needed here? I think in general these are set in the pom.xml native profile.

2020-07-31 09:30 UTC, cristianonicolai commented on process-mongodb-persistence-quarkus/src/main/resources/reflection-config.json
> +[
do we need reflection on this for Mongo?

2020-07-31 09:30 UTC, cristianonicolai commented on process-mongodb-persistence-quarkus/src/test/resources/application.properties
> +quarkus.native.additional-build-args =-H:ReflectionConfigurationFiles=reflection-config.json,\
please move native build options to pom native profile.

2020-08-03 03:52 UTC, swati-kale commented on process-mongodb-persistence-quarkus/src/main/resources/application.properties
> +quarkus.native.additional-build-args =-H:ReflectionConfigurationFiles=reflection-config.json,\
Not for mongodb related package but while converting JBPMMessages.java to json using protobuf-util. It does not recognize inner class and their methods.

2020-08-03 03:53 UTC, swati-kale commented on process-mongodb-persistence-quarkus/src/main/resources/reflection-config.json
> +[
Not for mongodb related package but while converting JBPMMessages.java to json using protobuf-util. It does not recognize inner class and their methods.

2020-08-03 03:54 UTC, swati-kale commented on process-mongodb-persistence-quarkus/src/test/resources/application.properties
> +quarkus.native.additional-build-args =-H:ReflectionConfigurationFiles=reflection-config.json,\
moved to pom.xml

2020-08-07 01:07 UTC, cristianonicolai commented on examples-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoMongoDBContainer.java
> +public class KogitoMongoDBContainer extends MongoDBContainer implements TestResource {
AFIK  examples-test-utils will be removed. You should be able to reuse this from kogito-test-utils in the runtime.

@Sgitario that's the plan right?

2020-08-07 06:30 UTC, Sgitario commented on examples-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoMongoDBContainer.java
> +public class KogitoMongoDBContainer extends MongoDBContainer implements TestResource {
That's correct. However, this module has not been deleted yet (it will be done as part of KOGITO-2985 which is blocked). So, it's fine to leave it this way at the moment).

2020-08-13 10:43 UTC, cristianonicolai commented
@swati-kale can you check the conflicts, thanks

2020-08-13 21:45 UTC, swati-kale commented
> @swati-kale can you check the conflicts, thanks

conflict resolved and rebase done.

2020-08-18 11:13 UTC, cristianonicolai commented
jenkins please retest this

2020-08-18 11:35 UTC, swati-kale commented on process-mongodb-persistence-quarkus/operator/process-mongodb-persistence-quarkus.yaml
> +  enablePersistence: true
The operator example will be handled in separate Jira.

2020-08-21 15:50 UTC, tiagodolphine commented
jenkins please retest this

2020-08-26 20:53 UTC, MarianMacik commented on process-mongodb-persistence-quarkus/README.md
> +For more details you can check applications.properties.
Maybe it would be good to add this also in the Spring Boot example readme.

2020-08-26 20:53 UTC, MarianMacik commented on process-mongodb-persistence-quarkus/src/main/java/org/acme/deals/Address.java
> +		this.country = country;
Formatting uses tabs instead of spaces.

2020-08-26 20:53 UTC, MarianMacik commented on process-mongodb-persistence-quarkus/src/main/java/org/acme/deals/Traveller.java
> +		this.firstName = firstName;
Same here, tabs instead of spaces.

2020-08-27 01:19 UTC, cristianonicolai commented on pom.xml
> +        <groupId>org.testcontainers</groupId>
can be removed as it now uses kogito-test-utils

2020-08-27 05:18 UTC, cristianonicolai commented
jenkins please retest this

2020-08-27 06:06 UTC, Sgitario approved these changes

2020-08-27 15:46 UTC, MarianMacik commented
jenkins please retest this

2020-08-27 17:56 UTC, MarianMacik commented
jenkins please retest this

2020-08-28 01:36 UTC, cristianonicolai commented
jenkins please retest this

2020-08-31 03:28 UTC, cristianonicolai commented
jenkins please retest this

2020-08-31 04:51 UTC, cristianonicolai commented
jenkins please retest this

2020-08-31 13:06 UTC, cristianonicolai commented
jenkins please retest this

2020-08-31 13:51 UTC, cristianonicolai commented
jenkins please retest this

2020-09-01 01:07 UTC, merged