KOGITO-2111 - Serverless Workflow - create event-based kogito example (quarkus)
apache/incubator-kie-examples pull request #254
Opened 2020-05-06 21:07 UTC by tsurdilo

2020-05-15 15:24 UTC, tsurdilo commented
rebased

@cristianonicolai @tiagodolphine @evacchi This is ready to be reviewed now :)

2020-05-18 02:37 UTC, cristianonicolai approved these changes

2020-05-18 02:40 UTC, cristianonicolai commented on serverless-workflow-events-quarkus/src/test/java/org/kogito/serverless/examples/KafkaResource.java
> +        return Collections.emptyMap();
you can return the _kafka.bootstrap.servers_ here and inject in the tests instead of using the system property, see https://github.com/kiegroup/kogito-examples/blob/master/process-kafka-quickstart-quarkus/src/test/java/org.acme.travel/KafkaTestResource.java#L43

2020-05-18 04:06 UTC, tsurdilo commented on serverless-workflow-events-quarkus/src/test/java/org/kogito/serverless/examples/KafkaResource.java
> +        return Collections.emptyMap();
Thanks for review @cristianonicolai!

I think regarding this comment, I like the way its now better honestly, and its the same way as used in quarkus quickstarts: https://github.com/quarkusio/quarkus-quickstarts/blob/master/kafka-quickstart/src/test/java/org/acme/kafka/KafkaResource.java
The sys prop gets cleaned up so imo it makes no difference really. Is this a must-have change?

2020-05-18 05:18 UTC, cristianonicolai commented on serverless-workflow-events-quarkus/src/test/java/org/kogito/serverless/examples/KafkaResource.java
> +        return Collections.emptyMap();
not a blocker @tsurdilo, its approved anyway

2020-05-21 15:03 UTC, ricardozanini requested changes
That's look really nice! Just small comments regarding the operator integration.

2020-05-21 15:03 UTC, ricardozanini commented on serverless-workflow-events-quarkus/operator/serverless-workflow-events-quarkus.yaml
> +      uri: 'https://github.com/kiegroup/kogito-examples'
Also add Kafka env here please: https://github.com/kiegroup/kogito-examples/blob/stable/process-kafka-quickstart-quarkus/operator/process-kafka-quickstart-quarkus.yaml#L6

2020-05-21 15:03 UTC, ricardozanini commented on serverless-workflow-events-quarkus/src/main/resources/application.properties
> +mp.messaging.outgoing.out-applicants.connector=smallrye-kafka
Could you please also add this property to make sure that Quarkus will allow us to inject the prperty via env var? https://github.com/kiegroup/kogito-examples/blob/stable/process-kafka-quickstart-quarkus/src/main/resources/application.properties#L3

2020-05-21 23:45 UTC, tsurdilo commented
@ricardozanini thanks for review! Updated per your recommendations. Thanks.

2020-05-25 16:45 UTC, ricardozanini approved these changes
@tiagodolphine do you have anything to add/review or we can merge this one?

Many thanks!

2020-05-25 17:37 UTC, tiagodolphine reviewed
@tsurdilo LGTM, I just made some minor comments.
Thanks

2020-05-25 17:37 UTC, tiagodolphine commented on serverless-workflow-events-quarkus/src/main/java/org/kogito/serverless/examples/ApplicantResource.java
> +        CloudEventImpl<JsonNode> applicantEvent =
You can use the interface `CloudEvent` instead of impl.

2020-05-25 17:37 UTC, tiagodolphine commented on serverless-workflow-events-quarkus/src/main/java/org/kogito/serverless/examples/ApplicantResource.java
> +                        .withId(String.valueOf(rand.nextInt(1000)))
what about `UUID.randomUUID() ` ?

2020-05-25 17:37 UTC, tiagodolphine commented on serverless-workflow-events-quarkus/src/main/java/org/kogito/serverless/examples/DecisionResource.java
> +    Publisher<JsonNode> decisions;
Can't it be a Publisher<String>? I mean to avoid using Jackson JsonNode?

2020-05-25 17:37 UTC, tiagodolphine commented on serverless-workflow-events-quarkus/src/main/resources/META-INF/resources/serializetojson.js
> +/**
I'm just wondering if adding the js file is really necessary, or could you use a reference to the source.

2020-05-25 17:37 UTC, tiagodolphine commented on serverless-workflow-events-quarkus/src/test/java/org/kogito/serverless/examples/ApplicantWorkflowTest.java
> +        JsonNode decisionObj = mapper.readTree(received.get(0));
Can't you use the CloudEvent here, like `mapper.readValue(received.get(0), CloudEvent.class)`?

2020-05-25 17:56 UTC, tsurdilo commented on serverless-workflow-events-quarkus/src/main/java/org/kogito/serverless/examples/ApplicantResource.java
> +        CloudEventImpl<JsonNode> applicantEvent =
I was using the i guess "recommended" way in the docs https://github.com/cloudevents/sdk-java/blob/master/README_v1.md. Think thats ok

2020-05-25 18:04 UTC, tsurdilo commented on serverless-workflow-events-quarkus/src/main/java/org/kogito/serverless/examples/ApplicantResource.java
> +                        .withId(String.valueOf(rand.nextInt(1000)))
great idea. updating

2020-05-25 18:05 UTC, tsurdilo commented on serverless-workflow-events-quarkus/src/main/java/org/kogito/serverless/examples/DecisionResource.java
> +    Publisher<JsonNode> decisions;
Its like this so it can easier be consumed by the workflow instance where the workflow data is JsonNode type.

2020-05-25 18:06 UTC, tsurdilo commented on serverless-workflow-events-quarkus/src/main/resources/META-INF/resources/serializetojson.js
> +/**
I could not find it before as a lib online, will look again now.

2020-05-25 18:12 UTC, tsurdilo commented on serverless-workflow-events-quarkus/src/test/java/org/kogito/serverless/examples/ApplicantWorkflowTest.java
> +        JsonNode decisionObj = mapper.readTree(received.get(0));
Can't do that mapping it seems unfortunately.

2020-05-25 18:23 UTC, tsurdilo commented
@tiagodolphine thanks for review! I updated just the uuid suggestion, for rest I rather keep it as is.
The only location of the script I found is

https://raw.githubusercontent.com/raphaelm22/jquery.serializeToJSON/master/src/jquery.serializeToJSON.js

However I cannot use/reference it inside a script task in html due to cors issues, sorry.

2020-05-26 15:50 UTC, tsurdilo commented
@cristianonicolai hi :) can this be merged please ?

2020-05-27 06:14 UTC, merged