[Kogito-2195] Kogito examples with ansible automation
apache/incubator-kie-examples pull request #258
Opened 2020-05-15 15:02 UTC by desmax74

https://issues.redhat.com/browse/KOGITO-2195
@sterobin @danielezonca

2020-05-15 15:33 UTC, sterobin commented
@krisv , @ricardozanini , @radtriste , who should we add as SME and QE reviewers for this to get it worked in and approved for the examples? Max and I apparently don't have permissions to add reviewers officially.

2020-05-18 10:09 UTC, jiripetrlik requested changes
@desmax74 
Hello! Thank you for your PR. I've put the first review here. Unfortunately I was not able to test it because the setup is for Ubuntu/Debian. Can you please add setup also for some RedHat like systems such as Fedora?

2020-05-18 10:09 UTC, jiripetrlik commented on kogito-ansible/README.md
> +No previous CRC setup (no /home/{user}/.crc folder), otherwise the create script will fail, delete .crc if you want run more than once the create playbook
Please make this optional. User may want to use his already CRC deployed cluster. It is probably not good to force user to remove all his previous CRC setup.

2020-05-18 10:09 UTC, jiripetrlik commented on kogito-ansible/README.md
> +Pre requisite on Debian/Ubuntu:
Please provide version of Ubuntu and Debian on which you have tested these scripts.

2020-05-18 10:09 UTC, jiripetrlik commented on kogito-ansible/README.md
> +
Please provide setup also for Fedora.

2020-05-18 10:09 UTC, jiripetrlik commented on kogito-ansible/playbook_libs.yaml
> +      shell: "sudo apt install qemu-kvm libvirt-daemon libvirt-daemon-system network-manager -y"
Please use "apt" module instead of shell. https://docs.ansible.com/ansible/latest/modules/apt_module.html#apt-module

2020-05-18 10:09 UTC, jiripetrlik commented on kogito-ansible/playbook_libs.yaml
> +      when: ansible_os_family == 'Debian'
Please check that os family is supported using assert module instead of silently skipping installation of libvirt libraries.
https://docs.ansible.com/ansible/latest/modules/assert_module.html#assert-module

2020-05-18 10:09 UTC, jiripetrlik commented on kogito-ansible/playbook_libs.yaml
> +  gather_facts: true
What is the reason for gather_facts here? As far as I know Ansible will gather facts automatically at start of the playbook.

2020-05-18 10:09 UTC, jiripetrlik commented on kogito-ansible/playbook_create.yaml
> +          url: "https://github.com/kiegroup/kogito-cloud-operator/releases/download/{{ kogito_tag }}/kogito-cli-{{ kogito_tag }}-linux-amd64.tar.gz"
Can you please specify variable for this with default value to make it configurable.

2020-05-18 10:09 UTC, jiripetrlik commented on kogito-ansible/playbook_create.yaml
> +          dest: "/tmp/kogito-{{ kogito_tag }}-linux-amd64.tar.gz"
Again please create variable for this temporary destination with default value. Or you can also consider to use "tempfile" module. https://docs.ansible.com/ansible/latest/modules/tempfile_module.html#tempfile-module

2020-05-18 10:09 UTC, jiripetrlik commented on kogito-ansible/playbook_etc_hosts.yaml
> +  - name: Check api in hosts
Isn't DNS reconfigured by CRC itself.

2020-05-18 10:09 UTC, jiripetrlik commented on kogito-ansible/playbook_create.yaml
> +      ip_on_etc_hosts: 192.168.130.11
Please do not use this value which can probably change on different machine etc. It would be much better to use "virt" or "virt_net" modules to obtain info about IP address.

- https://docs.ansible.com/ansible/latest/modules/virt_module.html#virt-module
- https://docs.ansible.com/ansible/latest/modules/virt_net_module.html#virt-net-module

2020-05-18 10:09 UTC, jiripetrlik commented on kogito-ansible/playbook_create.yaml
> +    gather_facts: true
Do we really need to explicitly run this?

2020-05-18 10:09 UTC, jiripetrlik commented on kogito-ansible/playbook_crc.yaml
> +  gather_facts: true
Isn't this done by default?

2020-05-18 10:11 UTC, jiripetrlik commented
@sterobin Hello I did the first QE review for this.

2020-05-18 10:17 UTC, desmax74 commented
@jiripetrlik These scripts are developed and tested on Fedora 31, only the playbook_scripts is for ubuntu if is the system used.

2020-05-18 10:26 UTC, jiripetrlik commented
@desmax74 It seems to me that "playbook_libs.yaml" is developed for Ubuntu isn't it? And as libvirts setup is necessary for whole setup we probably need alternative for Fedora. Do you agree?

2020-05-18 10:50 UTC, desmax74 commented
@jiripetrlik yep, only playbook_libs.yaml is for ubuntu, if isn't clear the description "Pre requisite on Debian/Ubuntu:
Install libvirt libs on Debian/Ubuntu only:" " I could change.
Libvirt was already present on Fedora iirc.

2020-05-18 10:51 UTC, desmax74 commented on kogito-ansible/playbook_crc.yaml
> +  gather_facts: true
No, is disabled by default to save time, but to read the current user infos is needed

2020-05-18 10:52 UTC, desmax74 commented on kogito-ansible/playbook_create.yaml
> +    gather_facts: true
No, was just to describe the version used, we could use a placeholder and print the version used instead to updated this on every update

2020-05-18 10:53 UTC, desmax74 commented on kogito-ansible/playbook_create.yaml
> +      ip_on_etc_hosts: 192.168.130.11
Ok

2020-05-18 10:54 UTC, desmax74 commented on kogito-ansible/playbook_libs.yaml
> +      shell: "sudo apt install qemu-kvm libvirt-daemon libvirt-daemon-system network-manager -y"
Ok

2020-05-18 10:54 UTC, desmax74 commented on kogito-ansible/playbook_libs.yaml
> +      when: ansible_os_family == 'Debian'
ok

2020-05-18 10:56 UTC, desmax74 commented on kogito-ansible/playbook_etc_hosts.yaml
> +  - name: Check api in hosts
I have to check with the latest version, because with old version of crc without this manual addition on /etc/hosts the cluster was unreachable

2020-05-18 10:56 UTC, desmax74 commented on kogito-ansible/playbook_create.yaml
> +          url: "https://github.com/kiegroup/kogito-cloud-operator/releases/download/{{ kogito_tag }}/kogito-cli-{{ kogito_tag }}-linux-amd64.tar.gz"
Ok

2020-05-18 10:57 UTC, desmax74 commented on kogito-ansible/playbook_create.yaml
> +          dest: "/tmp/kogito-{{ kogito_tag }}-linux-amd64.tar.gz"
Ok

2020-05-18 11:17 UTC, desmax74 commented on kogito-ansible/README.md
> +No previous CRC setup (no /home/{user}/.crc folder), otherwise the create script will fail, delete .crc if you want run more than once the create playbook
Ok

2020-05-18 11:17 UTC, desmax74 commented on kogito-ansible/README.md
> +Pre requisite on Debian/Ubuntu:
Ok

2020-05-18 11:21 UTC, desmax74 commented on kogito-ansible/README.md
> +
I'll create two sections in the doc since is all for fedora and only the lib virt installation is the first step on ubuntu

2020-05-18 11:25 UTC, jiripetrlik commented
@desmax74 
I would suggest to install "dnf install @virtualization" to be sure. Please use proper package module of Ansible to do that. Or check if libvirtd is running and in case that it does not install virtualization packages. To be honest don't know which packages are installed by default. But it may probably differ on Fedora type, such as desktop or server. Or it may be different for Fedora spins.

See documentation for Fedora virtualization packages: https://docs.fedoraproject.org/en-US/quick-docs/getting-started-with-virtualization/

2020-05-25 06:51 UTC, danielezonca reviewed
Thanks for the PR :)
Some comments

2020-05-25 06:51 UTC, danielezonca commented on kogito-ansible/README.md
> +Ansible must be installed.
Can you please add a link to https://docs.ansible.com/ansible/latest/installation_guide/index.html ?

2020-05-25 06:51 UTC, danielezonca commented on kogito-ansible/playbook_crc.yaml
> +    crc_package_name: "crc-linux-{{crc_version}}-amd64"
What about use `latest` path to have CRC version automatically updated ( https://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/ )?
As alternative it could be nice to let the user prompts the version

2020-05-25 06:51 UTC, danielezonca commented on kogito-ansible/playbook_create.yaml
> +      kogito_tag: "0.10.0"
Is it possible to get latest version from the project or update this value automatically? (a maven variable?)

2020-05-25 06:51 UTC, danielezonca commented on kogito-ansible/playbook_create.yaml
> +      libvirt_version: "4.4.3"
Why is this value hardcoded?

2020-05-25 06:51 UTC, danielezonca commented on README.md
> +## Deploying the Kogito example applications on OpenShift CRC using Ansible playbooks
I think it could be useful to add `locally` in the title: I don't think everyone know what CRC is.
You can change it as 
`Deploying the Kogito example applications locally with OpenShift CRC using Ansible playbooks`

2020-05-25 06:51 UTC, danielezonca commented on kogito-ansible/README.md
> +Ansible must be installed.
Can you please refactor this paragraph as `Prerequisite`?
Can you please add to this section also system requirement needs in terms of RAM and disk?

2020-05-25 06:51 UTC, danielezonca commented on kogito-ansible/playbook_deploy.yaml
> +      libvirt_version: "4.4.3"
Same comment about hardcoded version.

2020-05-25 06:51 UTC, danielezonca commented on kogito-ansible/playbook_create.yaml
> +        shell: xmllint --xpath '/*[local-name()="project"]/*[local-name()="modules"]' /tmp/examples_pom.xml > ~/.crc/quarkus_examples.txt
Why `quarkus`? Is this script limited to quarkus example?
If yes why?
If not I would prefer to name it `kogito-examples.txt`

2020-05-25 06:51 UTC, danielezonca commented on kogito-ansible/playbook_deploy.yaml
> +        default: "\n{{ examples }}"
Can you please clarify what does it mean?
By default will this deploy `all` kogito examples in the same namespace?

2020-05-25 06:51 UTC, danielezonca commented on kogito-ansible/README.md
> +## Ubuntu
Is this section actually different from the `Fedora` one?
They are really similar (the same?) from what I can see. Is it possible to create a single `Fedora/Ubuntu` section and just highlight different steps (if any).
This can reduce maintenance cost of this doc :)

2020-05-25 07:56 UTC, jiripetrlik commented on kogito-ansible/playbook_libs.yaml
> +      shell: "sudo dnf install @virtualization -y"
Please use Ansible DNF module instead https://docs.ansible.com/ansible/latest/modules/dnf_module.html#dnf-module

Something like this:
    - name: Install Virtualization on Fedora
      dnf:
        name: "@virtualization"
      become: yes
      when: ansible_os_family == 'RedHat'

2020-05-25 08:55 UTC, desmax74 commented on kogito-ansible/README.md
> +Ansible must be installed.
ok

2020-05-25 09:00 UTC, desmax74 commented on README.md
> +## Deploying the Kogito example applications on OpenShift CRC using Ansible playbooks
ok

2020-05-25 09:00 UTC, desmax74 commented on kogito-ansible/README.md
> +Ansible must be installed.
ok

2020-05-25 09:11 UTC, desmax74 commented on kogito-ansible/playbook_create.yaml
> +      libvirt_version: "4.4.3"
Because is used in the path and you discover the version only when the crc is downloaded and unpacked

2020-05-25 09:11 UTC, desmax74 commented on kogito-ansible/playbook_deploy.yaml
> +      libvirt_version: "4.4.3"
Because is used in the path and you discover the version only when the crc is downloaded and unpacked

2020-05-25 09:12 UTC, desmax74 commented on kogito-ansible/playbook_create.yaml
> +        shell: xmllint --xpath '/*[local-name()="project"]/*[local-name()="modules"]' /tmp/examples_pom.xml > ~/.crc/quarkus_examples.txt
ok, I'll rename kogito-examples

2020-05-25 09:14 UTC, desmax74 commented on kogito-ansible/playbook_deploy.yaml
> +        default: "\n{{ examples }}"
It deploy only the choosed example, default is only the message to display

2020-05-25 09:15 UTC, desmax74 commented on kogito-ansible/README.md
> +## Ubuntu
Previously only one section plus the ubuntu lib virt installation was present but at the reviewer seems a document for ubuntu deploy and asked a fedora version, for this reason you see  explicit configurations for both systems

2020-05-25 09:16 UTC, desmax74 commented on kogito-ansible/playbook_libs.yaml
> +      shell: "sudo dnf install @virtualization -y"
ok

2020-05-25 10:16 UTC, danielezonca commented on kogito-ansible/README.md
> +## Ubuntu
I agree to have the instructions for `Ubuntu` and `Fedora` too but if they are the same just mention that the instructions are tested on both configuration instead of duplicate them :)

2020-05-25 20:33 UTC, desmax74 commented on kogito-ansible/playbook_create.yaml
> +      libvirt_version: "4.4.3"
I've writed a version to use the latest kogito tag, but the 0.10.1 doesn't work because the cli and the operator aren't aligned  (kogito 0.10.1 - kogito-cloud-operator 0.10.0)

2020-05-26 07:15 UTC, danielezonca commented on kogito-ansible/playbook_create.yaml
> +      libvirt_version: "4.4.3"
mmm I expect this could happen in the future too so is it possible to add a `kogito-operator` variable to support also this use case?

2020-05-27 15:07 UTC, jiripetrlik commented
@desmax74 
I've found two possible bugs when installing on fresh Ubuntu 20.04.

1. In playbook "playbook_crc", "crc libvirt group" task. Crc can not be found because folder ".local/bin" did not exist before running Ansible script, To workaround this it is necessary to reinitialize terminal and run command manually "crc config set skip-check-user-in-libvirt-group true"

2. In "playbook_create" in "Start CRC with 13312MB" task. I see the following error: "Failed to query DNS from host: lookup api.crc.testing: no such host"

2020-05-27 15:34 UTC, desmax74 commented
@jiripetrlik 
1) Why not just simply create the folder as a pre-task ?

2) I could re-apply https://github.com/kiegroup/kogito-examples/pull/258/commits/654af19b9bd72e3ca642579ef3ac0e1786c13239#diff-5ab00d684a07bbdf26507b898ba2a2ff

2020-05-29 11:25 UTC, jiripetrlik commented
@desmax74 
ad 1, I've moved "Create .local/bin/" task to pre_tasks but without any effect. It is still necessary to login and logout to have crc command on PATH.
ad 2, I've tried to run "kogito-ansible/playbook_etc_hosts.yaml" before playbook_create but it failed with the following error "Failed to query DNS from host: lookup foo.apps-crc.testing: no such host". I think we need to find more general solution than adding lines to hosts file for each domain. Is CRC supported on Debian/Ubuntu?

2020-05-29 14:05 UTC, desmax74 commented
In the Ubuntu 20.04 bashrc isn't present the `PATH="$HOME/.local/bin` 
I'll change the script to change the bashrc to re add like the 19.10

2020-05-29 14:23 UTC, danielezonca commented on kogito-ansible/playbook_create.yaml
> +      private: "no"
Can you split in two different values? You can propose by default the same value user specified in the first step. Something like (I don't know Ansible syntax so it could be wrong)
```yaml
    - name: "kogitoTag"
      default: "0.10.0"
      prompt: "Kogito Version"
      private: "no"
    - name: "kogitoOperator"
      default: {{ kogitoTag }}
      prompt: "Kogito Operator version"
      private: "no"
```
Wdyt?

2020-05-29 14:50 UTC, desmax74 commented on kogito-ansible/playbook_create.yaml
> +      private: "no"
Is up to kogito the installation of the operator and it didn't pass values like version, we ask the kogito version just to decide which version to download https://github.com/kiegroup/kogito-examples/pull/258/files#diff-a5f485f8a086810799bb19ca584ec530R150

2020-06-04 07:53 UTC, danielezonca approved these changes
Approving :+1: 
@desmax74 can you please rebase from master to make the build green?

2020-06-09 13:21 UTC, desmax74 commented
@jiripetrlik dropped ubuntu until we found a workaround, please review

2020-06-16 09:01 UTC, jiripetrlik commented
@desmax74 Hello currently I'm getting following error on Fedora 32 : ""changed": true, "cmd": "crc setup", "delta": "0:03:00.977265", "end": "2020-06-16 10:31:41.176060", "msg": "non-zero return code", "rc": 1, "start": "2020-06-16 10:28:40.198795", "stderr": "level=fatal msg=\"Failed to start libvirt 'crc' network\"", "stderr_lines"...

2020-06-16 09:17 UTC, jiripetrlik commented
@desmax74 It also seems that there are some commits unrelated to PR and PR check failed. Can you please rebase properly?

2024-03-01 07:30 UTC, domhanak commented
@krisv @mdproctor @ricardozanini do you have any information about this?

2024-03-01 12:57 UTC, ricardozanini commented
I'd close it.

2025-01-30 13:42 UTC, domhanak commented
Closing as stale

2025-01-30 13:42 UTC, closed without merging