KOGITO-1867: Move docker image property definitions to parent pom
apache/incubator-kie-examples pull request #278
Opened 2020-06-17 12:14 UTC by Sgitario

JIRA: https://issues.redhat.com/browse/KOGITO-1867
Description:
- Remove the container keycloak configuration from examples and move them to the parent module.
- Normalize the Keycloak container as done in the Infinispan container.

2020-06-17 13:27 UTC, sutaakar commented
Does it mean that all examples will share same Keycloak realm?

2020-06-17 13:32 UTC, Sgitario commented
> Does it mean that all examples will share same Keycloak realm?

For integration tests, they will. However, it's possible to overwrite it in a concrete test.

2020-06-17 13:48 UTC, cristianonicolai approved these changes

2020-06-17 13:50 UTC, sutaakar approved these changes

2020-06-17 15:03 UTC, radtriste approved these changes

2020-06-18 06:28 UTC, jstastny-cz requested changes

2020-06-18 06:28 UTC, jstastny-cz commented on examples-test-utils/src/main/java/org/kie/kogito/testcontainers/KeycloakContainer.java
> +        setDockerImageName(System.getProperty(KEYCLOAK_PROPERTY, "quay.io/keycloak/keycloak:8.0.1"));
could we turn the image specs to a constant too? KEYCLOAK_IMAGE for example? so that it's in top of the class definition.

2020-06-18 06:28 UTC, jstastny-cz commented on examples-test-utils/src/main/java/org/kie/kogito/testcontainers/quarkus/ConditionalQuarkusResource.java
> +public abstract class ConditionalQuarkusResource implements QuarkusTestResourceLifecycleManager {
Since the class is called `ConditionalQuarkusResource` I would expect this to be a general use test resource, but it's tightly coupled with the containers, the name should reflect that too. Plus I would also keep the full substring `TestResource` as part of the name.

Wouldn't here be more general approach to extend the `QUarkusTestResourceLifecycleManager` interface by a method like `boolean isEnabled()` that would then be used in start/stop. That we can call ConditionalTestResource and then by all means having an abstract class that introduces the container support to be extended by particular testcontainers based test resources.

2020-06-18 06:28 UTC, jstastny-cz commented on examples-test-utils/src/main/java/org/kie/kogito/testcontainers/quarkus/KeycloakQuarkusResource.java
> +public class KeycloakQuarkusResource extends ConditionalQuarkusResource {
I would keep the word `TestResource` in names.

2020-06-18 06:30 UTC, Sgitario commented on examples-test-utils/src/main/java/org/kie/kogito/testcontainers/KeycloakContainer.java
> +        setDockerImageName(System.getProperty(KEYCLOAK_PROPERTY, "quay.io/keycloak/keycloak:8.0.1"));
Sorry, this is a leftover. I will remove it instead.

2020-06-18 07:25 UTC, Sgitario commented on examples-test-utils/src/main/java/org/kie/kogito/testcontainers/quarkus/ConditionalQuarkusResource.java
> +public abstract class ConditionalQuarkusResource implements QuarkusTestResourceLifecycleManager {
If I understood correctly your comment, you are proposing either (a) to rename this class with a better name as this is tightly coupled with testcontainers, or (b) isolate it from testcontainers.

I partly did (b). Ideally, the ConditionalGenericContainer class should be isolated as well, but this would not be compatible with the builder pattern: doing this.enableIfTestCategoryIs().withEnv("x", "y), and for spring boot, I think this is quite useful as it allows to set your container in one line. 

Let me know if you're ok with these changes. Thanks!

2020-06-18 07:26 UTC, Sgitario commented on examples-test-utils/src/main/java/org/kie/kogito/testcontainers/quarkus/KeycloakQuarkusResource.java
> +public class KeycloakQuarkusResource extends ConditionalQuarkusResource {
Renamed this and InfinispanQuarkusResource.

2020-06-18 08:25 UTC, jstastny-cz commented on examples-test-utils/src/main/java/org/kie/kogito/resources/ConditionalTestResource.java
> +public interface ConditionalTestResource<T> {
I meant extending `QuarkusTestResourceLifecycleManager` here and implementing just this in `ConditionalQuarkusTestResource`
`public abstract class ConditionalQuarkusTestResource implements ConditionalTestResource`.

2020-06-18 10:06 UTC, Sgitario commented on examples-test-utils/src/main/java/org/kie/kogito/resources/ConditionalTestResource.java
> +public interface ConditionalTestResource<T> {
As agreed, I've already renamed the field to conditionalResource. Thanks for spotting this!

2020-06-18 10:33 UTC, jstastny-cz approved these changes
Just a small nitpick, otherwise looks good.

2020-06-18 10:33 UTC, jstastny-cz commented on process-usertasks-with-security-oidc-springboot/src/test/java/org/acme/travels/ApprovalsRestIT.java
> +    public static KeycloakContainer KEYCLOAK = new KeycloakContainer();
can be still final, right?

2020-06-18 10:35 UTC, Sgitario commented on process-usertasks-with-security-oidc-springboot/src/test/java/org/acme/travels/ApprovalsRestIT.java
> +    public static KeycloakContainer KEYCLOAK = new KeycloakContainer();
Sure. Re-added.

2020-06-19 01:08 UTC, merged