KOGITO-2773: Update scesim example enabling compatibility with BC
apache/incubator-kie-examples pull request #389
Opened 2020-10-13 07:58 UTC by yesamer

https://issues.redhat.com/browse/KOGITO-2773

The real name of "Type" column is "Type" and not "string". The editor will show "string" but, under the cover, "Type" is used because is a "Anonymous" DMNType (a type with allowed values). This change will enable the example to be both compatible with Kogito channels and Business Central

- [ ] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

2020-10-13 13:35 UTC, danielezonca approved these changes
LGTM :+1:

2020-10-13 13:52 UTC, jstastny-cz approved these changes

2020-10-13 14:03 UTC, jstastny-cz requested changes
I am getting `Impossible to load file. Error: Not supported: http://javax.xml.XMLConstants/property/accessExternalDTD` in BC, is there any matching PR that needs to be merged together?

2020-10-13 14:08 UTC, yesamer commented
> I am getting `Impossible to load file. Error: Not supported: http://javax.xml.XMLConstants/property/accessExternalDTD` in BC, is there any matching PR that needs to be merged together?

@jstastny-cz That was another bug which I already solved https://github.com/kiegroup/drools/pull/3158. Since tomorrow builds it should disappear.

2020-10-13 14:10 UTC, jstastny-cz commented
I'll finish the review tomorrow.

2020-10-14 14:03 UTC, jstastny-cz approved these changes

2020-10-14 14:09 UTC, yesamer commented
@kiegroup/gatekeepers Can you please merge it?

2020-10-15 08:29 UTC, merged