[KOGITO-4279] Add health extension to Quarkus examples
apache/incubator-kie-examples pull request #538
Opened 2021-01-27 13:51 UTC by Kevin-Mok

See: https://issues.redhat.com/browse/KOGITO-4279

This PR makes the Quarkus examples pass the HTTP liveness/readiness checks when deployed on OpenShift as per [KOGITO-4210](https://issues.redhat.com/browse/KOGITO-4210).

## Implementation
I wrote a simple `fish` script to automate adding the extension to the Quarkus directories:
```fish
for dir in (ls -d */)
    # don't match Spring Boot dirs
    if test -z (string match '*springboot*' $dir)
        cd $dir
        and ../mvnw quarkus:add-extension -Dextensions="smallrye-health"

        cd ..
    end
end
```

This removes all comments from the `pom.xml`, so I manually added back the necessary ones.

## Requirements
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `master` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

2021-01-27 14:52 UTC, sutaakar commented
@Kevin-Mok The script seems to add
```
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-bom</artifactId>
        <version>1.11.0.Final</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```
IMHO it is not needed as the quarkus bom is transitively imported by kogito-quarkus-bom

2021-01-27 17:02 UTC, Kevin-Mok commented
I removed it using another script. :sweat_smile: 
```fish
for pom in (rg -lt xml kogito-quarkus-bom)
    perl -p0e 's/.*<dependency>\n.*\n.*<artifactId>quarkus-bom<\/artifactId>\n.*\n.*\n.*\n.*<\/dependency>\n//g' -i $pom
end
```

2021-01-27 19:26 UTC, ricardozanini reviewed
@Kevin-Mok seems fine. But I'm curious about the dependency management on this huge project. I believe we can add the dependency to the parent `pom`, having it propagated to all modules. This way, people writing new examples won't miss this one. But since it's only for Quarkus, I think we might need to break the example BOM for each runtime. :thinking: 

@danielezonca wdyt?

2021-01-27 19:26 UTC, ricardozanini commented on serverless-workflow-github-showcase/pom.xml
> +        <scope>import</scope>
I think we don't need this. Your script missed this one. :smile:

2021-01-27 19:26 UTC, ricardozanini commented on serverless-workflow-temperature-conversion/multiplication-service/pom.xml
> +<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
Actually, we need to be `https` instead. It's a security requirement.

2021-01-28 00:07 UTC, Kevin-Mok commented on serverless-workflow-github-showcase/pom.xml
> +        <scope>import</scope>
The two containing this ([serverless-workflow-github-showcase](https://github.com/kiegroup/kogito-examples/blob/master/serverless-workflow-github-showcase/pom.xml), [serverless-workflow-temperature-conversion](https://github.com/kiegroup/kogito-examples/blob/master/serverless-workflow-temperature-conversion/pom.xml)) don't have a `kogito-quarkus` or `kogito-quarkus-bom` dependency though. :thinking:

2021-01-28 12:27 UTC, sutaakar commented on kogito-travel-agency/extended/pom.xml
> +      <artifactId>quarkus-smallrye-health</artifactId>
This declaration can be removed as the dependency is defined in child modules.

2021-01-28 12:28 UTC, sutaakar commented on kogito-travel-agency/pom.xml
> +      <artifactId>quarkus-smallrye-health</artifactId>
Same here.

2021-01-28 12:29 UTC, sutaakar commented on onboarding-example/pom.xml
> +      <artifactId>quarkus-smallrye-health</artifactId>
And here.

2021-01-28 14:40 UTC, ricardozanini commented on serverless-workflow-github-showcase/pom.xml
> +        <scope>import</scope>
'cause they are parent modules, and the sub-modules are not Kogito projects. :sweat:

2021-01-28 14:59 UTC, ricardozanini commented on kogito-travel-agency/extended/pom.xml
> +      <artifactId>quarkus-smallrye-health</artifactId>
Hey @sutaakar! What about keeping in the parents and removing from child modules? The same for the Serverless Workflow examples that have sub-modules.

2021-01-28 15:59 UTC, sutaakar commented on kogito-travel-agency/extended/pom.xml
> +      <artifactId>quarkus-smallrye-health</artifactId>
fine for me

2021-01-28 20:31 UTC, ricardozanini approved these changes

2021-01-29 12:32 UTC, sutaakar approved these changes

2021-01-29 12:33 UTC, sutaakar commented
@Kevin-Mok Can you please fix the build error? The health extension cannot be resolved in serverless-workflow-github-showcase as there is no bom imported.

2021-02-03 14:23 UTC, Kevin-Mok commented
The check seems to be failing on the Spring Boot example for onboarding. I made [these changes](https://github.com/kiegroup/kogito-examples/pull/538/files#diff-23c1e48ecfdb7e05de0a44264b8e42bfabdc96202bd16874eca21c738b03d01d) to that particular POM, which were just from auto-generation. I don't think they're the reason for the failure though.

*Edit*: @sutaakar helped me figure out that the Spring Boot portion of the onboarding example is incompatible with the health extension, so I just removed it from the parent module and added it to all the other submodules except Spring Boot.

2021-02-05 07:51 UTC, cristianonicolai requested changes
@Kevin-Mok it doesnt haelp much the review with so many changes not directly related to the PR goal. I would suggest next time send a PR just for reformat things separately.

2021-02-05 07:51 UTC, cristianonicolai commented on serverless-workflow-temperature-conversion/pom.xml
> +        <version>1.11.1.Final</version>
this dependency is probably not needed, each of the services already defines a dependency to quarkus, just add the smallrye-helath in there

2021-02-05 07:51 UTC, cristianonicolai commented on serverless-workflow-github-showcase/pom.xml
> +        <scope>import</scope>
+1, this dependency is not needed, please add into the submodules directly.

2021-02-05 16:03 UTC, Kevin-Mok commented on serverless-workflow-github-showcase/pom.xml
> +        <scope>import</scope>
@ricardozanini suggested adding it to [only the parent modules](https://github.com/kiegroup/kogito-examples/pull/538#discussion_r566160859), but the build fails if you remove this `quarkus-universe-bom` dependency as @sutaakar [pointed out](https://github.com/kiegroup/kogito-examples/pull/538#issuecomment-769778993).  

```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for io.quarkus:quarkus-smallrye-health:jar is missing. @ line 19, column 17
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.kie.kogito:serverless-workflow-temperature-conversion:2.0.0-SNAPSHOT (/home/kevin/coding/kogito/kogito-examples/serverless-workflow-temperature-conversion/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for io.quarkus:quarkus-smallrye-health:jar is missing. @ line 19, column 17
```

@ricardozanini, should I just move it into the submodules to get rid of this dependency then?

2021-02-05 18:17 UTC, ricardozanini commented on serverless-workflow-github-showcase/pom.xml
> +        <scope>import</scope>
Yeah, add them directly then.

2021-02-08 13:21 UTC, ricardozanini commented
@cristianonicolai can you take a second look?

2021-02-08 14:21 UTC, cristianonicolai approved these changes

2021-02-08 16:56 UTC, merged