Use admin user to install Kogito Operator
apache/incubator-kie-examples pull request #56
Opened 2019-07-26 13:30 UTC by sutaakar

The ordinary user doesn't have rights for this.
@ricardozanini Could you please review?

2019-07-26 13:41 UTC, ricardozanini requested changes

2019-07-26 13:41 UTC, ricardozanini commented on openshift-example-tests/src/main/java/org/kogito/examples/openshift/deployment/OperatorDeployer.java
> +        project.getAdmin().createServiceAccount(serviceAccount);
The Operator Service Account will be created within the Operator https://issues.jboss.org/browse/KOGITO-66. I understand that you need this now, but you should remember to remove it as soon as I fix this JIRA. :p

2019-07-26 13:41 UTC, ricardozanini commented on openshift-example-tests/src/main/java/org/kogito/examples/openshift/deployment/OperatorDeployer.java
> +        project.getAdmin().rbac().roles().inNamespace(project.getName()).create(role);
See above, same for the bindings. We could end up with duplicated content. Or this user need to be created to run the Operator?

2019-07-26 13:51 UTC, sutaakar commented on openshift-example-tests/src/main/java/org/kogito/examples/openshift/deployment/OperatorDeployer.java
> +        project.getAdmin().rbac().roles().inNamespace(project.getName()).create(role);
These steps are actually required to install Kogito Operator itself. They are not related to actions done by Kogito Operator when building an application using CRs.

2019-07-26 15:58 UTC, ricardozanini commented on openshift-example-tests/src/main/java/org/kogito/examples/openshift/deployment/OperatorDeployer.java
> +        project.getAdmin().rbac().roles().inNamespace(project.getName()).create(role);
Sure!

2019-07-26 15:58 UTC, ricardozanini approved these changes

2019-07-29 14:40 UTC, mswiderski approved these changes

2019-07-29 14:40 UTC, merged