KOGITO-4972: Enable security on infinispan container in process-usert…
apache/incubator-kie-examples pull request #654
Opened 2021-04-20 11:21 UTC by nmirasch

…asks-with-security-oidc-quarkus-with-console example

jira: https://issues.redhat.com/browse/KOGITO-4972

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

2021-04-20 14:34 UTC, nmirasch commented
@cristianonicolai @radtriste I have added authentication on infinispan to share application.properties and don't break the native build.
The only way found to make the sample work was using the nightly version of data-index. Is there any issue with keeping it nightly?
Could you take a look? Thanks!

2021-04-20 14:36 UTC, radtriste requested changes

2021-04-20 14:36 UTC, radtriste commented on process-usertasks-with-security-oidc-quarkus-with-console/docker-compose/docker-compose.yml
> +    image: quay.io/kiegroup/kogito-data-index-infinispan-nightly:${KOGITO_VERSION}
please set back to prod image ;)
https://issues.redhat.com/browse/KOGITO-4609 is supposed to enable nightlies in master and then to replace once released

2021-04-20 14:45 UTC, cristianonicolai commented on process-usertasks-with-security-oidc-quarkus-with-console/docker-compose/docker-compose.yml
> +    image: quay.io/kiegroup/kogito-data-index-infinispan-nightly:${KOGITO_VERSION}
@nmirasch yeah we shouldnt use nightly here. Now that 1.5 has been released, using latest doesnt fix the issue?

2021-04-20 15:11 UTC, radtriste approved these changes

2021-04-20 15:52 UTC, nmirasch commented on process-usertasks-with-security-oidc-quarkus-with-console/docker-compose/docker-compose.yml
> +    image: quay.io/kiegroup/kogito-data-index-infinispan-nightly:${KOGITO_VERSION}
@cristianonicolai The 'latest' I'm getting is 5 days old and with that, this example in my environment is not working properly.  I've restored the image reference to use the latest, but if you can give this a chance and confirm that is something that only happens in my environment, would be great.

2021-04-21 09:34 UTC, cristianonicolai approved these changes

2021-04-21 09:37 UTC, cristianonicolai commented
@nmirasch it works fine if versions are aligned, snapshot and nightly or 1.5.0.Final for both, otherwise it fails because of this fix: https://github.com/kiegroup/kogito-apps/pull/737. Basically in that context we have different attributes sent in the payload. This should work fine once it goes into stable branch.

2021-04-21 09:38 UTC, merged