[KOGITO-5284] Change OnBoarding example to use new Kubernetes Add-on
apache/incubator-kie-examples pull request #929
Opened 2021-10-11 20:04 UTC by ricardozanini

Signed-off-by: Ricardo Zanini <zanini@redhat.com>

See https://issues.redhat.com/browse/KOGITO-5284
Depends on:
- https://github.com/kiegroup/kogito-runtimes/pull/1648

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

**WARNING! Please make sure you are opening your PR against `main` branch!**

- [x] You have read the [contributors guide](https://github.com/kiegroup/kogito-runtimes#contributing-to-kogito)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

</details>

2021-10-13 15:47 UTC, spolti requested changes

2021-10-13 15:47 UTC, spolti commented on onboarding-example/README.md
> +- [GraalVM 19.1.1](https://github.com/oracle/graal/releases/tag/vm-19.1.1) installed
I guess the version for graalvm now is 21.x

2021-10-13 15:47 UTC, spolti commented on onboarding-example/README.md
> +- Maven 3.6.2+ installed
isn't maven 3.8+ now required?

2021-10-13 21:07 UTC, ricardozanini commented on onboarding-example/README.md
> +- [GraalVM 19.1.1](https://github.com/oracle/graal/releases/tag/vm-19.1.1) installed
We need to update all the examples then, if I have some leftovers in this one, I'll change. Otherwise we should do a batch sed replace in the entire structure.

2021-10-13 21:08 UTC, ricardozanini commented on onboarding-example/README.md
> +- Maven 3.6.2+ installed
Same answer.

2021-10-14 20:41 UTC, danielezonca approved these changes
LGTM, only a single real comment about jkube plugin declaration 👍

2021-10-14 20:41 UTC, danielezonca commented on onboarding-example/payroll/src/main/resources/application.properties
> +# quarkus.knative.labels.payments/date=process
We can probably create a [custom profile](https://quarkus.io/guides/config-reference#custom-profiles) for knative 🤔

2021-10-14 20:41 UTC, danielezonca commented on onboarding-example/onboarding-quarkus/src/main/resources/application.properties
> +# quarkus.knative.labels.onboarding=process
Same here

2021-10-14 20:41 UTC, danielezonca commented on onboarding-example/hr/src/main/resources/application.properties
> +# quarkus.knative.labels.employee-validation/first=process
Same here

2021-10-14 20:41 UTC, danielezonca commented on onboarding-example/onboarding-springboot/pom.xml
> +            <groupId>org.eclipse.jkube</groupId>
Ok now I see that it is used here (see [comment](https://github.com/infinispan/infinispan-spring-boot/issues/168)).
I think it is better to declare it [here](https://github.com/kiegroup/kogito-examples/blob/main/pom.xml#L473) instead of in kogito-runtimes. Wdyt?

2021-10-15 05:47 UTC, cristianonicolai commented on onboarding-example/README.md
> +- [GraalVM 19.1.1](https://github.com/oracle/graal/releases/tag/vm-19.1.1) installed
I think we should have the basic requirements listed in the root level README of the repository, then examples can just point to there, so we avoid having to update these in multiple places, wdyt?

2021-10-15 05:53 UTC, cristianonicolai approved these changes

2021-10-15 05:53 UTC, cristianonicolai commented on onboarding-example/hr/src/main/resources/application.properties
> +quarkus.container-image.group=kogito
I think we have been using 
```suggestion
quarkus.container-image.group=org.kie.kogito
```

2021-10-15 18:49 UTC, ricardozanini commented on onboarding-example/hr/src/main/resources/application.properties
> +quarkus.container-image.group=kogito
This is not a namespace but how the image will be defined in the registry. In this example, the image will be something like `kogito/hr-service`. Usually, we do not use namespace names for image groups.

2021-10-25 18:33 UTC, merged